# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\auth\ui_authentication.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_form_auth_prompt(object):
    def setupUi(self, dlg_form_auth_prompt):
        dlg_form_auth_prompt.setObjectName("dlg_form_auth_prompt")
        dlg_form_auth_prompt.resize(700, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlg_form_auth_prompt.sizePolicy().hasHeightForWidth())
        dlg_form_auth_prompt.setSizePolicy(sizePolicy)
        dlg_form_auth_prompt.setMinimumSize(QtCore.QSize(700, 280))
        dlg_form_auth_prompt.setMaximumSize(QtCore.QSize(700, 280))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_form_auth_prompt.setWindowIcon(icon)
        dlg_form_auth_prompt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        dlg_form_auth_prompt.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_form_auth_prompt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgbar_vlayout = QtWidgets.QVBoxLayout()
        self.msgbar_vlayout.setObjectName("msgbar_vlayout")
        self.verticalLayout.addLayout(self.msgbar_vlayout)
        self.lbl_browse_credentials = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_browse_credentials.sizePolicy().hasHeightForWidth())
        self.lbl_browse_credentials.setSizePolicy(sizePolicy)
        self.lbl_browse_credentials.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_browse_credentials.setFont(font)
        self.lbl_browse_credentials.setAutoFillBackground(False)
        self.lbl_browse_credentials.setScaledContents(True)
        self.lbl_browse_credentials.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_browse_credentials.setObjectName("lbl_browse_credentials")
        self.verticalLayout.addWidget(self.lbl_browse_credentials)
        self.btn_browse_credentials = QgsFileWidget(dlg_form_auth_prompt)
        self.btn_browse_credentials.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse_credentials.sizePolicy().hasHeightForWidth())
        self.btn_browse_credentials.setSizePolicy(sizePolicy)
        self.btn_browse_credentials.setMinimumSize(QtCore.QSize(200, 25))
        self.btn_browse_credentials.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_browse_credentials.setFont(font)
        self.btn_browse_credentials.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_browse_credentials.setAcceptDrops(False)
        self.btn_browse_credentials.setFileWidgetButtonVisible(True)
        self.btn_browse_credentials.setUseLink(False)
        self.btn_browse_credentials.setFullUrl(False)
        self.btn_browse_credentials.setFilter("*.json")
        self.btn_browse_credentials.setDefaultRoot("")
        self.btn_browse_credentials.setObjectName("btn_browse_credentials")
        self.verticalLayout.addWidget(self.btn_browse_credentials)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_api_url = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api_url.sizePolicy().hasHeightForWidth())
        self.lbl_api_url.setSizePolicy(sizePolicy)
        self.lbl_api_url.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_api_url.setFont(font)
        self.lbl_api_url.setAutoFillBackground(False)
        self.lbl_api_url.setScaledContents(True)
        self.lbl_api_url.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_api_url.setObjectName("lbl_api_url")
        self.verticalLayout_4.addWidget(self.lbl_api_url)
        self.lbl_app_id = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_id.sizePolicy().hasHeightForWidth())
        self.lbl_app_id.setSizePolicy(sizePolicy)
        self.lbl_app_id.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_app_id.setFont(font)
        self.lbl_app_id.setAutoFillBackground(False)
        self.lbl_app_id.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_id.setScaledContents(True)
        self.lbl_app_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_id.setObjectName("lbl_app_id")
        self.verticalLayout_4.addWidget(self.lbl_app_id)
        self.lbl_app_secret = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_secret.sizePolicy().hasHeightForWidth())
        self.lbl_app_secret.setSizePolicy(sizePolicy)
        self.lbl_app_secret.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_app_secret.setFont(font)
        self.lbl_app_secret.setAutoFillBackground(False)
        self.lbl_app_secret.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_secret.setScaledContents(True)
        self.lbl_app_secret.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_secret.setObjectName("lbl_app_secret")
        self.verticalLayout_4.addWidget(self.lbl_app_secret)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_api_url_value = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api_url_value.sizePolicy().hasHeightForWidth())
        self.lbl_api_url_value.setSizePolicy(sizePolicy)
        self.lbl_api_url_value.setMinimumSize(QtCore.QSize(300, 25))
        self.lbl_api_url_value.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lbl_api_url_value.setFont(font)
        self.lbl_api_url_value.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lbl_api_url_value.setAutoFillBackground(False)
        self.lbl_api_url_value.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_api_url_value.setText("https://v1.api.isogeo.com/")
        self.lbl_api_url_value.setOpenExternalLinks(True)
        self.lbl_api_url_value.setObjectName("lbl_api_url_value")
        self.verticalLayout_3.addWidget(self.lbl_api_url_value)
        self.ent_app_id = QtWidgets.QLineEdit(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_id.sizePolicy().hasHeightForWidth())
        self.ent_app_id.setSizePolicy(sizePolicy)
        self.ent_app_id.setMinimumSize(QtCore.QSize(200, 25))
        self.ent_app_id.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ent_app_id.setFont(font)
        self.ent_app_id.setToolTip("")
        self.ent_app_id.setAutoFillBackground(True)
        self.ent_app_id.setText("")
        self.ent_app_id.setMaxLength(100)
        self.ent_app_id.setFrame(True)
        self.ent_app_id.setReadOnly(True)
        self.ent_app_id.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ent_app_id.setObjectName("ent_app_id")
        self.verticalLayout_3.addWidget(self.ent_app_id)
        self.ent_app_secret = QtWidgets.QLineEdit(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_secret.sizePolicy().hasHeightForWidth())
        self.ent_app_secret.setSizePolicy(sizePolicy)
        self.ent_app_secret.setMinimumSize(QtCore.QSize(200, 25))
        self.ent_app_secret.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ent_app_secret.setFont(font)
        self.ent_app_secret.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ent_app_secret.setAutoFillBackground(True)
        self.ent_app_secret.setText("")
        self.ent_app_secret.setMaxLength(64)
        self.ent_app_secret.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.ent_app_secret.setReadOnly(True)
        self.ent_app_secret.setPlaceholderText("*******************************************")
        self.ent_app_secret.setObjectName("ent_app_secret")
        self.verticalLayout_3.addWidget(self.ent_app_secret)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.chb_isogeo_editor = QtWidgets.QCheckBox(dlg_form_auth_prompt)
        self.chb_isogeo_editor.setMinimumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chb_isogeo_editor.setFont(font)
        self.chb_isogeo_editor.setToolTip("")
        self.chb_isogeo_editor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chb_isogeo_editor.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/authentication/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chb_isogeo_editor.setIcon(icon1)
        self.chb_isogeo_editor.setTristate(False)
        self.chb_isogeo_editor.setObjectName("chb_isogeo_editor")
        self.verticalLayout.addWidget(self.chb_isogeo_editor)
        self.btn_ok_cancel = QtWidgets.QDialogButtonBox(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btn_ok_cancel.sizePolicy().hasHeightForWidth())
        self.btn_ok_cancel.setSizePolicy(sizePolicy)
        self.btn_ok_cancel.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_ok_cancel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_ok_cancel.setFont(font)
        self.btn_ok_cancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_ok_cancel.setAutoFillBackground(False)
        self.btn_ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.btn_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btn_ok_cancel.setCenterButtons(True)
        self.btn_ok_cancel.setObjectName("btn_ok_cancel")
        self.verticalLayout.addWidget(self.btn_ok_cancel)

        self.retranslateUi(dlg_form_auth_prompt)
        self.btn_ok_cancel.accepted.connect(dlg_form_auth_prompt.accept)
        self.btn_ok_cancel.rejected.connect(dlg_form_auth_prompt.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_form_auth_prompt)

    def retranslateUi(self, dlg_form_auth_prompt):
        _translate = QtCore.QCoreApplication.translate
        dlg_form_auth_prompt.setWindowTitle(_translate("dlg_form_auth_prompt", "Isogeo authentication settings"))
        self.lbl_browse_credentials.setText(_translate("dlg_form_auth_prompt", "From a file:"))
        self.btn_browse_credentials.setToolTip(_translate("dlg_form_auth_prompt", "Pick your credentials file"))
        self.btn_browse_credentials.setDialogTitle(_translate("dlg_form_auth_prompt", "Locate the Isogeo API credentials file"))
        self.lbl_api_url.setToolTip(_translate("dlg_form_auth_prompt", "Only for information, the Isogeo API base URL"))
        self.lbl_api_url.setText(_translate("dlg_form_auth_prompt", "API location:"))
        self.lbl_app_id.setText(_translate("dlg_form_auth_prompt", "Application ID:"))
        self.lbl_app_secret.setText(_translate("dlg_form_auth_prompt", "Application SECRET:"))
        self.ent_app_id.setPlaceholderText(_translate("dlg_form_auth_prompt", "plugin-qgis-org-a1b23c4d5f6g7h8i9j10kl11mn13op14"))
        self.chb_isogeo_editor.setText(_translate("dlg_form_auth_prompt", "I\'ve got edition rights on app.isogeo.com"))

from qgsfilewidget import QgsFileWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg_form_auth_prompt = QtWidgets.QDialog()
    ui = Ui_dlg_form_auth_prompt()
    ui.setupUi(dlg_form_auth_prompt)
    dlg_form_auth_prompt.show()
    sys.exit(app.exec_())

