# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\auth\ui_authentication.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_form_auth_prompt(object):
    def setupUi(self, dlg_form_auth_prompt):
        dlg_form_auth_prompt.setObjectName("dlg_form_auth_prompt")
        dlg_form_auth_prompt.setEnabled(True)
        dlg_form_auth_prompt.resize(700, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlg_form_auth_prompt.sizePolicy().hasHeightForWidth())
        dlg_form_auth_prompt.setSizePolicy(sizePolicy)
        dlg_form_auth_prompt.setMinimumSize(QtCore.QSize(700, 220))
        dlg_form_auth_prompt.setMaximumSize(QtCore.QSize(700, 220))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/settings/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_form_auth_prompt.setWindowIcon(icon)
        dlg_form_auth_prompt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(dlg_form_auth_prompt)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_browse_credentials = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_browse_credentials.sizePolicy().hasHeightForWidth())
        self.lbl_browse_credentials.setSizePolicy(sizePolicy)
        self.lbl_browse_credentials.setMinimumSize(QtCore.QSize(0, 23))
        self.lbl_browse_credentials.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_browse_credentials.setFont(font)
        self.lbl_browse_credentials.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_browse_credentials.setScaledContents(True)
        self.lbl_browse_credentials.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_browse_credentials.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_browse_credentials.setObjectName("lbl_browse_credentials")
        self.verticalLayout.addWidget(self.lbl_browse_credentials)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.lbl_app_id = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_id.sizePolicy().hasHeightForWidth())
        self.lbl_app_id.setSizePolicy(sizePolicy)
        self.lbl_app_id.setMinimumSize(QtCore.QSize(0, 23))
        self.lbl_app_id.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lbl_app_id.setFont(font)
        self.lbl_app_id.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_app_id.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_id.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_id.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_app_id.setObjectName("lbl_app_id")
        self.verticalLayout.addWidget(self.lbl_app_id)
        self.lbl_app_id_2 = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_app_id_2.sizePolicy().hasHeightForWidth())
        self.lbl_app_id_2.setSizePolicy(sizePolicy)
        self.lbl_app_id_2.setMinimumSize(QtCore.QSize(0, 23))
        self.lbl_app_id_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lbl_app_id_2.setFont(font)
        self.lbl_app_id_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_app_id_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_app_id_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_app_id_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_app_id_2.setObjectName("lbl_app_id_2")
        self.verticalLayout.addWidget(self.lbl_app_id_2)
        self.lbl_api_url = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api_url.sizePolicy().hasHeightForWidth())
        self.lbl_api_url.setSizePolicy(sizePolicy)
        self.lbl_api_url.setMinimumSize(QtCore.QSize(0, 23))
        self.lbl_api_url.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.lbl_api_url.setFont(font)
        self.lbl_api_url.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_api_url.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_api_url.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_api_url.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_api_url.setObjectName("lbl_api_url")
        self.verticalLayout.addWidget(self.lbl_api_url)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_browse_credentials = QgsFileWidget(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_browse_credentials.sizePolicy().hasHeightForWidth())
        self.btn_browse_credentials.setSizePolicy(sizePolicy)
        self.btn_browse_credentials.setMinimumSize(QtCore.QSize(0, 23))
        self.btn_browse_credentials.setMaximumSize(QtCore.QSize(690, 30))
        self.btn_browse_credentials.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btn_browse_credentials.setFileWidgetButtonVisible(True)
        self.btn_browse_credentials.setFilter("*.json")
        self.btn_browse_credentials.setDefaultRoot("")
        self.btn_browse_credentials.setObjectName("btn_browse_credentials")
        self.verticalLayout_3.addWidget(self.btn_browse_credentials)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.ent_app_id = QtWidgets.QLineEdit(dlg_form_auth_prompt)
        self.ent_app_id.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_id.sizePolicy().hasHeightForWidth())
        self.ent_app_id.setSizePolicy(sizePolicy)
        self.ent_app_id.setMinimumSize(QtCore.QSize(0, 23))
        self.ent_app_id.setMaximumSize(QtCore.QSize(690, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.ent_app_id.setFont(font)
        self.ent_app_id.setAutoFillBackground(False)
        self.ent_app_id.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ent_app_id.setReadOnly(True)
        self.ent_app_id.setPlaceholderText("plugin-qgis-org-a1b23c4d5f6g7h8i9j10kl11mn13op14")
        self.ent_app_id.setObjectName("ent_app_id")
        self.verticalLayout_3.addWidget(self.ent_app_id)
        self.ent_app_secret = QtWidgets.QLineEdit(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ent_app_secret.sizePolicy().hasHeightForWidth())
        self.ent_app_secret.setSizePolicy(sizePolicy)
        self.ent_app_secret.setMinimumSize(QtCore.QSize(0, 23))
        self.ent_app_secret.setMaximumSize(QtCore.QSize(690, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.ent_app_secret.setFont(font)
        self.ent_app_secret.setAutoFillBackground(False)
        self.ent_app_secret.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ent_app_secret.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.ent_app_secret.setReadOnly(True)
        self.ent_app_secret.setPlaceholderText("*******************************************")
        self.ent_app_secret.setObjectName("ent_app_secret")
        self.verticalLayout_3.addWidget(self.ent_app_secret)
        self.lbl_api_url_value = QtWidgets.QLabel(dlg_form_auth_prompt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_api_url_value.sizePolicy().hasHeightForWidth())
        self.lbl_api_url_value.setSizePolicy(sizePolicy)
        self.lbl_api_url_value.setMinimumSize(QtCore.QSize(0, 23))
        self.lbl_api_url_value.setMaximumSize(QtCore.QSize(583, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(False)
        font.setWeight(50)
        self.lbl_api_url_value.setFont(font)
        self.lbl_api_url_value.setAutoFillBackground(False)
        self.lbl_api_url_value.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lbl_api_url_value.setText("https://v1.api.isogeo.com/")
        self.lbl_api_url_value.setOpenExternalLinks(True)
        self.lbl_api_url_value.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_api_url_value.setObjectName("lbl_api_url_value")
        self.verticalLayout_3.addWidget(self.lbl_api_url_value)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.chb_isogeo_editor = QtWidgets.QCheckBox(dlg_form_auth_prompt)
        self.chb_isogeo_editor.setMinimumSize(QtCore.QSize(690, 20))
        self.chb_isogeo_editor.setMaximumSize(QtCore.QSize(690, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.chb_isogeo_editor.setFont(font)
        self.chb_isogeo_editor.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/users_blue.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chb_isogeo_editor.setIcon(icon1)
        self.chb_isogeo_editor.setObjectName("chb_isogeo_editor")
        self.verticalLayout_2.addWidget(self.chb_isogeo_editor)
        self.btn_ok_cancel = QtWidgets.QDialogButtonBox(dlg_form_auth_prompt)
        self.btn_ok_cancel.setMinimumSize(QtCore.QSize(690, 30))
        self.btn_ok_cancel.setMaximumSize(QtCore.QSize(690, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.btn_ok_cancel.setFont(font)
        self.btn_ok_cancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_ok_cancel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btn_ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.btn_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btn_ok_cancel.setCenterButtons(True)
        self.btn_ok_cancel.setObjectName("btn_ok_cancel")
        self.verticalLayout_2.addWidget(self.btn_ok_cancel)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.msgbar_vlayout = QtWidgets.QVBoxLayout()
        self.msgbar_vlayout.setSpacing(4)
        self.msgbar_vlayout.setObjectName("msgbar_vlayout")
        self.gridLayout.addLayout(self.msgbar_vlayout, 0, 0, 1, 1)

        self.retranslateUi(dlg_form_auth_prompt)
        self.btn_ok_cancel.accepted.connect(dlg_form_auth_prompt.accept)
        self.btn_ok_cancel.rejected.connect(dlg_form_auth_prompt.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_form_auth_prompt)

    def retranslateUi(self, dlg_form_auth_prompt):
        _translate = QtCore.QCoreApplication.translate
        dlg_form_auth_prompt.setWindowTitle(_translate("dlg_form_auth_prompt", "Isogeo authentication settings"))
        self.lbl_browse_credentials.setText(_translate("dlg_form_auth_prompt", "From a file:"))
        self.lbl_app_id.setText(_translate("dlg_form_auth_prompt", "Application ID:"))
        self.lbl_app_id_2.setText(_translate("dlg_form_auth_prompt", "Application SECRET:"))
        self.lbl_api_url.setText(_translate("dlg_form_auth_prompt", "API location:"))
        self.btn_browse_credentials.setToolTip(_translate("dlg_form_auth_prompt", "Pick your credentials file"))
        self.btn_browse_credentials.setDialogTitle(_translate("dlg_form_auth_prompt", "Locate the Isogeo API credentials file"))
        self.chb_isogeo_editor.setText(_translate("dlg_form_auth_prompt", "I\'ve got edition rights on app.isogeo.com"))

from qgsfilewidget import QgsFileWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg_form_auth_prompt = QtWidgets.QDialog()
    ui = Ui_dlg_form_auth_prompt()
    ui.setupUi(dlg_form_auth_prompt)
    dlg_form_auth_prompt.show()
    sys.exit(app.exec_())

