# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IsogeoDockWidget
                                 A QGIS plugin
 Recherchez des données via un ou plusieurs catalogues Isogeo
                             -------------------
        begin                : 2015-12-22
        git sha              : $Format:%H$
        copyright            : (C) 2015 by GeoJulien/Isogeo
        email                : projets@isogeo.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt4 import QtGui, uic
from PyQt4.QtCore import pyqtSignal

# # changed because of an issue generated by Qt Designer
# # see: http://gis.stackexchange.com/a/155599/19817
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ui_md_details.ui'))

# from ui_md_details import Ui_MetadataDetails


# # changed besause of an issue generated by Qt Designer
# # see: http://gis.stackexchange.com/a/155599/19817
# class IsogeoMdDetails(QtGui.QDialog, FORM_CLASS):

class IsogeoMdDetails(QtGui.QDialog, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(IsogeoMdDetails, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
