# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isogeo_md_details.ui'
#
# Created: Tue Sep 06 15:00:26 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MetadataDetails(object):
    def setupUi(self, MetadataDetails):
        MetadataDetails.setObjectName(_fromUtf8("MetadataDetails"))
        MetadataDetails.resize(1031, 712)
        self.gridLayout_6 = QtGui.QGridLayout(MetadataDetails)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lbl_title = QtGui.QLabel(MetadataDetails)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setWordWrap(True)
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.gridLayout_6.addWidget(self.lbl_title, 0, 0, 1, 3)
        self.grp_ident = QtGui.QGroupBox(MetadataDetails)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_ident.sizePolicy().hasHeightForWidth())
        self.grp_ident.setSizePolicy(sizePolicy)
        self.grp_ident.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_ident.setMaximumSize(QtCore.QSize(16777215, 141))
        self.grp_ident.setObjectName(_fromUtf8("grp_ident"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grp_ident)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbl_owner = QtGui.QLabel(self.grp_ident)
        self.lbl_owner.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_owner.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_owner.setText(_fromUtf8(""))
        self.lbl_owner.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/staff.svg")))
        self.lbl_owner.setScaledContents(True)
        self.lbl_owner.setObjectName(_fromUtf8("lbl_owner"))
        self.gridLayout_3.addWidget(self.lbl_owner, 0, 0, 1, 1)
        self.val_owner = QtGui.QTextEdit(self.grp_ident)
        self.val_owner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.val_owner.setReadOnly(True)
        self.val_owner.setObjectName(_fromUtf8("val_owner"))
        self.gridLayout_3.addWidget(self.val_owner, 0, 1, 1, 1)
        self.lbl_abstract = QtGui.QLabel(self.grp_ident)
        self.lbl_abstract.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_abstract.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_abstract.setText(_fromUtf8(""))
        self.lbl_abstract.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/font.svg")))
        self.lbl_abstract.setScaledContents(True)
        self.lbl_abstract.setObjectName(_fromUtf8("lbl_abstract"))
        self.gridLayout_3.addWidget(self.lbl_abstract, 0, 2, 1, 1)
        self.val_abstract = QtGui.QTextEdit(self.grp_ident)
        self.val_abstract.setReadOnly(True)
        self.val_abstract.setObjectName(_fromUtf8("val_abstract"))
        self.gridLayout_3.addWidget(self.val_abstract, 0, 3, 3, 1)
        self.lbl_keywords = QtGui.QLabel(self.grp_ident)
        self.lbl_keywords.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_keywords.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_keywords.setText(_fromUtf8(""))
        self.lbl_keywords.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/tags.svg")))
        self.lbl_keywords.setScaledContents(True)
        self.lbl_keywords.setWordWrap(False)
        self.lbl_keywords.setObjectName(_fromUtf8("lbl_keywords"))
        self.gridLayout_3.addWidget(self.lbl_keywords, 1, 0, 1, 1)
        self.val_keywords = QtGui.QTextEdit(self.grp_ident)
        self.val_keywords.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.val_keywords.setReadOnly(True)
        self.val_keywords.setObjectName(_fromUtf8("val_keywords"))
        self.gridLayout_3.addWidget(self.val_keywords, 1, 1, 1, 1)
        self.lbl_inspire_themes = QtGui.QLabel(self.grp_ident)
        self.lbl_inspire_themes.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_inspire_themes.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_inspire_themes.setText(_fromUtf8(""))
        self.lbl_inspire_themes.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/leaf.svg")))
        self.lbl_inspire_themes.setScaledContents(True)
        self.lbl_inspire_themes.setObjectName(_fromUtf8("lbl_inspire_themes"))
        self.gridLayout_3.addWidget(self.lbl_inspire_themes, 2, 0, 1, 1)
        self.val_inspire_themes = QtGui.QTextEdit(self.grp_ident)
        self.val_inspire_themes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.val_inspire_themes.setReadOnly(True)
        self.val_inspire_themes.setObjectName(_fromUtf8("val_inspire_themes"))
        self.gridLayout_3.addWidget(self.val_inspire_themes, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.grp_ident, 1, 0, 2, 2)
        self.grp_technic = QtGui.QGroupBox(MetadataDetails)
        self.grp_technic.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_technic.setObjectName(_fromUtf8("grp_technic"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grp_technic)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lbl_format = QtGui.QLabel(self.grp_technic)
        self.lbl_format.setMinimumSize(QtCore.QSize(131, 0))
        self.lbl_format.setObjectName(_fromUtf8("lbl_format"))
        self.horizontalLayout_5.addWidget(self.lbl_format)
        self.val_format = QtGui.QLabel(self.grp_technic)
        self.val_format.setObjectName(_fromUtf8("val_format"))
        self.horizontalLayout_5.addWidget(self.val_format)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lbl_srs = QtGui.QLabel(self.grp_technic)
        self.lbl_srs.setMinimumSize(QtCore.QSize(131, 0))
        self.lbl_srs.setObjectName(_fromUtf8("lbl_srs"))
        self.horizontalLayout_6.addWidget(self.lbl_srs)
        self.val_srs = QtGui.QLabel(self.grp_technic)
        self.val_srs.setObjectName(_fromUtf8("val_srs"))
        self.horizontalLayout_6.addWidget(self.val_srs)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grp_technic, 1, 2, 1, 1)
        self.grp_contacts = QgsCollapsibleGroupBox(MetadataDetails)
        self.grp_contacts.setMinimumSize(QtCore.QSize(391, 0))
        self.grp_contacts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_contacts.setCheckable(False)
        self.grp_contacts.setObjectName(_fromUtf8("grp_contacts"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grp_contacts)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.val_contact = QtGui.QTextEdit(self.grp_contacts)
        self.val_contact.setReadOnly(True)
        self.val_contact.setObjectName(_fromUtf8("val_contact"))
        self.gridLayout_2.addWidget(self.val_contact, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grp_contacts, 2, 2, 2, 1)
        self.grp_history = QtGui.QGroupBox(MetadataDetails)
        self.grp_history.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_history.setObjectName(_fromUtf8("grp_history"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grp_history)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.line_3 = QtGui.QFrame(self.grp_history)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_4.addWidget(self.line_3, 0, 1, 3, 2)
        self.line_4 = QtGui.QFrame(self.grp_history)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_4.addWidget(self.line_4, 0, 3, 3, 1)
        self.lbl_last_events = QtGui.QLabel(self.grp_history)
        self.lbl_last_events.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_last_events.setText(_fromUtf8(""))
        self.lbl_last_events.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar.svg")))
        self.lbl_last_events.setScaledContents(True)
        self.lbl_last_events.setObjectName(_fromUtf8("lbl_last_events"))
        self.gridLayout_4.addWidget(self.lbl_last_events, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.grp_history)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 5, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_data_crea = QtGui.QLabel(self.grp_history)
        self.lbl_data_crea.setObjectName(_fromUtf8("lbl_data_crea"))
        self.horizontalLayout.addWidget(self.lbl_data_crea)
        self.val_data_crea = QtGui.QLabel(self.grp_history)
        self.val_data_crea.setObjectName(_fromUtf8("val_data_crea"))
        self.horizontalLayout.addWidget(self.val_data_crea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_data_updt = QtGui.QLabel(self.grp_history)
        self.lbl_data_updt.setObjectName(_fromUtf8("lbl_data_updt"))
        self.horizontalLayout_2.addWidget(self.lbl_data_updt)
        self.val_data_updt = QtGui.QLabel(self.grp_history)
        self.val_data_updt.setObjectName(_fromUtf8("val_data_updt"))
        self.horizontalLayout_2.addWidget(self.val_data_updt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 2, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbl_valid_start = QtGui.QLabel(self.grp_history)
        self.lbl_valid_start.setObjectName(_fromUtf8("lbl_valid_start"))
        self.horizontalLayout_3.addWidget(self.lbl_valid_start)
        self.val_valid_start = QtGui.QLabel(self.grp_history)
        self.val_valid_start.setObjectName(_fromUtf8("val_valid_start"))
        self.horizontalLayout_3.addWidget(self.val_valid_start)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_valid_end = QtGui.QLabel(self.grp_history)
        self.lbl_valid_end.setObjectName(_fromUtf8("lbl_valid_end"))
        self.horizontalLayout_4.addWidget(self.lbl_valid_end)
        self.val_valid_end = QtGui.QLabel(self.grp_history)
        self.val_valid_end.setObjectName(_fromUtf8("val_valid_end"))
        self.horizontalLayout_4.addWidget(self.val_valid_end)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 2, 2, 1)
        self.list_events = QtGui.QListWidget(self.grp_history)
        self.list_events.setMinimumSize(QtCore.QSize(215, 0))
        self.list_events.setObjectName(_fromUtf8("list_events"))
        self.gridLayout_4.addWidget(self.list_events, 2, 4, 1, 2)
        self.gridLayout_6.addWidget(self.grp_history, 3, 0, 2, 2)
        self.grp_fields = QtGui.QGroupBox(MetadataDetails)
        self.grp_fields.setObjectName(_fromUtf8("grp_fields"))
        self.gridLayout = QtGui.QGridLayout(self.grp_fields)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbl_attributes = QtGui.QTableWidget(self.grp_fields)
        self.tbl_attributes.setObjectName(_fromUtf8("tbl_attributes"))
        self.tbl_attributes.setColumnCount(3)
        self.tbl_attributes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tbl_attributes, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grp_fields, 4, 2, 3, 1)
        self.groupBox = QtGui.QGroupBox(MetadataDetails)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lbl_context = QtGui.QLabel(self.groupBox)
        self.lbl_context.setObjectName(_fromUtf8("lbl_context"))
        self.gridLayout_8.addWidget(self.lbl_context, 0, 0, 1, 1)
        self.lbl_method = QtGui.QLabel(self.groupBox)
        self.lbl_method.setObjectName(_fromUtf8("lbl_method"))
        self.gridLayout_8.addWidget(self.lbl_method, 0, 1, 1, 1)
        self.val_context = QtGui.QTextEdit(self.groupBox)
        self.val_context.setMinimumSize(QtCore.QSize(271, 0))
        self.val_context.setReadOnly(True)
        self.val_context.setObjectName(_fromUtf8("val_context"))
        self.gridLayout_8.addWidget(self.val_context, 1, 0, 1, 1)
        self.val_method = QtGui.QTextEdit(self.groupBox)
        self.val_method.setMinimumSize(QtCore.QSize(271, 0))
        self.val_method.setReadOnly(True)
        self.val_method.setObjectName(_fromUtf8("val_method"))
        self.gridLayout_8.addWidget(self.val_method, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 5, 0, 1, 2)
        self.grp_limitations = QtGui.QGroupBox(MetadataDetails)
        self.grp_limitations.setObjectName(_fromUtf8("grp_limitations"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grp_limitations)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.val_limitations = QtGui.QTextEdit(self.grp_limitations)
        self.val_limitations.setReadOnly(True)
        self.val_limitations.setObjectName(_fromUtf8("val_limitations"))
        self.gridLayout_7.addWidget(self.val_limitations, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grp_limitations, 6, 0, 1, 1)
        self.grp_conditions = QtGui.QGroupBox(MetadataDetails)
        self.grp_conditions.setObjectName(_fromUtf8("grp_conditions"))
        self.gridLayout_9 = QtGui.QGridLayout(self.grp_conditions)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.val_conditions = QtGui.QTextEdit(self.grp_conditions)
        self.val_conditions.setReadOnly(True)
        self.val_conditions.setObjectName(_fromUtf8("val_conditions"))
        self.gridLayout_9.addWidget(self.val_conditions, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grp_conditions, 6, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(MetadataDetails)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 7, 2, 1, 1)

        self.retranslateUi(MetadataDetails)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MetadataDetails.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MetadataDetails.reject)
        QtCore.QMetaObject.connectSlotsByName(MetadataDetails)

    def retranslateUi(self, MetadataDetails):
        MetadataDetails.setWindowTitle(_translate("MetadataDetails", "Dialog", None))
        self.lbl_title.setText(_translate("MetadataDetails", "<html><head/><body><p><span style=\" font-style:italic;\">NR</span></p></body></html>", None))
        self.grp_ident.setTitle(_translate("MetadataDetails", "Identification", None))
        self.grp_technic.setTitle(_translate("MetadataDetails", "Informations techniques", None))
        self.lbl_format.setText(_translate("MetadataDetails", "Format :", None))
        self.val_format.setText(_translate("MetadataDetails", "TextLabel", None))
        self.lbl_srs.setText(_translate("MetadataDetails", "SRS : ", None))
        self.val_srs.setText(_translate("MetadataDetails", "TextLabel", None))
        self.grp_contacts.setTitle(_translate("MetadataDetails", "Contacts", None))
        self.grp_history.setTitle(_translate("MetadataDetails", "Historique de la donnée", None))
        self.label.setText(_translate("MetadataDetails", "Dernières modifications", None))
        self.lbl_data_crea.setText(_translate("MetadataDetails", "Date de création :", None))
        self.val_data_crea.setText(_translate("MetadataDetails", "TextLabel", None))
        self.lbl_data_updt.setText(_translate("MetadataDetails", "Mise à jour :", None))
        self.val_data_updt.setText(_translate("MetadataDetails", "TextLabel", None))
        self.lbl_valid_start.setText(_translate("MetadataDetails", "Début de validité :", None))
        self.val_valid_start.setText(_translate("MetadataDetails", "TextLabel", None))
        self.lbl_valid_end.setText(_translate("MetadataDetails", "Fin de validité :", None))
        self.val_valid_end.setText(_translate("MetadataDetails", "TextLabel", None))
        self.grp_fields.setTitle(_translate("MetadataDetails", "Attributs", None))
        item = self.tbl_attributes.horizontalHeaderItem(0)
        item.setText(_translate("MetadataDetails", "Nom", None))
        item = self.tbl_attributes.horizontalHeaderItem(1)
        item.setText(_translate("MetadataDetails", "Type", None))
        item = self.tbl_attributes.horizontalHeaderItem(2)
        item.setText(_translate("MetadataDetails", "Description", None))
        self.groupBox.setTitle(_translate("MetadataDetails", "Collecte", None))
        self.lbl_context.setText(_translate("MetadataDetails", "Contexte de collecte :", None))
        self.lbl_method.setText(_translate("MetadataDetails", "Méthode de collecte :", None))
        self.grp_limitations.setTitle(_translate("MetadataDetails", "Limitations", None))
        self.grp_conditions.setTitle(_translate("MetadataDetails", "Conditions", None))

from qgis.gui import QgsCollapsibleGroupBox
