services:
    - docker

sudo: false

env:
  global:
    - IMAGE=qgis/qgis
    - PLUGIN_NAME=Isogeo

  matrix:
    - QGIS_VERSION_TAG=release-3_4
    # - QGIS_VERSION_TAG=release-3_8
    #- QGIS_VERSION_TAG=latest

dist: xenial
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.7"

# branches:
#   only:
#     - master

addons:
  apt:
    packages:
      - pyqt5-dev-tools
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - python -m pip install -U pip setuptools wheel black
  # run the qgis container naming it as 'qgis-testing-environment'
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/${PLUGIN_NAME} -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  # This is required to allow xvfb to start
  - sleep 10
  # Setup qgis and enables the plugin
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
  # Fix the symlink created by qgis_setup.sh
  - docker exec  -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/${PLUGIN_NAME}"
  - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/${PLUGIN_NAME}"


script:
  # - docker exec -it qgis-testing-environment sh -c "cd /${PLUGIN_NAME} && qgis_testrunner.sh tests.test_Plugin"
  - docker exec -it qgis-testing-environment sh -c "cd /${PLUGIN_NAME} && ls -a"
  - docker exec -it qgis-testing-environment sh -c "cd /${PLUGIN_NAME} && python3 tools/plugin_packager.py"

