services:
    - docker

sudo: false

env:
  global:
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_VERSION_TAG=release-3_4
    # - QGIS_VERSION_TAG=release-3_8
    #- QGIS_VERSION_TAG=latest


language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

# branches:
#   only:
#     - master

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - python -m pip install -U pip setuptools wheel black
  - pip install --upgrade pep257
  - pip install --upgrade flake8
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/isogeo-plugin-qgis -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10

script:
  - python -m black --target-version=py37 /isogeo-plugin-qgis/
