language: python
dist: trusty

python:
  - "2.7"

virtualenv:
  system_site_packages: true

cache:
  apt: true
  pip: true

branches:
  only:
    - master

git:
  depth: 20

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb https://qgis.org/ubuntu-ltr/ trusty main'
    packages:
      - python-software-properties
      - qgis
      - python-qgis
      - pyqt4-dev-tools

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - pylupdate4 -noobsolete -verbose isogeo_search_engine.pro
  - pyuic4 -x "ui/isogeo_dockwidget_base.ui" -o "ui/ui_isogeo.py"
  - python tools/plugin_packager.py
