# Lint, test and package a plugin for QGIS
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

# CONDITIONS WHICH TRIGGER OR NOT THE JOBS
trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

# -- GLOBAL VARIABLES ------------------------------------------------------------------
variables:
  PLUGIN_NAME: Isogeo
  QGIS_VERSION_TAG: release-3_10
  QGIS_IMAGE: qgis/qgis
  pythonVersion: "3.7"
  vmImageName: "windows-2019"
  VERSION_NAME: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]
  VERSION_SUFIX: $[replace(variables['VERSION_NAME'], '.', '_')]

# -- STAGES ----------------------------------------------------------------------------
stages:

- stage: Lint
  # -- LINT AND FORMAT -----------------------------------------------------------------
  displayName: Format and lint code
  jobs:

  # LINT AND FORMATTING CODE
  - job: 'Lint'
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
      fetchDepth: 10

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)
        architecture: 'x64'
        addToPath: true

    - script: |
        python -m pip install -U pip --cache-dir ./.pipcache
        python -m pip install -U -r ./requirements.txt --cache-dir ./.pipcache
      displayName: 'Install dependencies'

    - script: |
        python -m black --target-version=py37 .\isogeo.py
        python -m black --target-version=py37 .\modules
        python -m black --target-version=py37 .\tools
        python -m black --target-version=py37 .\tests
        python -m black --target-version=py37 .\ui
      displayName: "Apply black code formatting"

    - script: |
        flake8 ./isogeo.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./modules --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./isogeo.py --count --exit-zero --max-complexity=10 --max-line-length=100
        flake8 ./modules --count --exit-zero --max-complexity=10 --max-line-length=100
      displayName: "Static code analisis: PEP8 conformance, imports... (flake8)"

    # save formatted code to use later avoiding git clone again
    - publish: $(System.DefaultWorkingDirectory)
      artifact: "FORMATTED_$(pyPiPackageName)_$(Build.SourceBranchName)_$(Build.BuildId)"
      displayName: "Publish formatted code with dependencies"

- stage: Build
  # --  BUILD --------------------------------------------------------------------------
  displayName: "Build and package"
  dependsOn: Lint
  condition: |
    and(
      succeeded(),
      ne(variables['System.PullRequest.SourceBranch'], 'docs')
    )

  jobs:
  # UI COMPILATION
  - job: "BuildUi"  # only letters and numbers (no space...)
    displayName: "Qt - compilation and internationalization"  # can't contain special characters
    pool:
      vmImage: $(vmImageName)

    steps:
    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifact: "FORMATTED_$(pyPiPackageName)_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)"

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)
        architecture: 'x64'
        addToPath: true

    - script: |
        python -m pip install -U pip --cache-dir ./.pipcache
        python -m pip install -U -r ./requirements.txt --cache-dir ./.pipcache
      displayName: 'Install dependencies'

    - script: |
        pylupdate5 -noobsolete -verbose isogeo_search_engine.pro
        lrelease .\i18n\isogeo_search_engine_en.ts
        lrelease .\i18n\isogeo_search_engine_fr.ts
      displayName: "Qt: processing translations (i18n)"

    - script: |
        pyrcc5 resources.qrc -o resources_rc.py
      displayName: "Qt: processing resources compilation"

    - script: |
        pyuic5 -x "ui\isogeo_dockwidget_base.ui" -o "ui\ui_isogeo.py"
        pyuic5 -x "ui\auth\ui_authentication.ui" -o "ui\auth\ui_authentication.py"
        pyuic5 -x "ui\credits\ui_credits.ui" -o "ui\credits\ui_credits.py"
        pyuic5 -x "ui\db_connections\ui_db_connections.ui" -o "ui\db_connections\ui_db_connections.py"
        pyuic5 -x "ui\metadata\ui_md_details.ui" -o "ui\metadata\ui_md_details.py"
        pyuic5 -x "ui\quicksearch\ui_quicksearch_rename.ui" -o "ui\quicksearch\ui_quicksearch_rename.py"
        pyuic5 -x "ui\quicksearch\ui_quicksearch_new.ui" -o "ui\quicksearch\ui_quicksearch_new.py"
      displayName: "Qt: processing UI files compilation"

    - task: PublishPipelineArtifact@1
      displayName: "Publish artifact: Qt stuff compiled"
      inputs:
        path: $(System.DefaultWorkingDirectory)
        artifact: "COMPILED_$(Build.SourceBranchName)_$(Build.BuildId)"

  # UI COMPILATION
  - job: "Packaging"  # only letters and numbers (no space...)
    displayName: "Packaging the plugin"  # can't contain special characters
    dependsOn: "BuildUi"
    pool:
      vmImage: $(vmImageName)

    steps:

    # no need for source code
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifactName: "COMPILED_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)"

    - task: UsePythonVersion@0
      displayName: "Install Python"
      inputs:
        versionSpec: $(pythonVersion)
        architecture: "x64"
        addToPath: true

    - script: python ./tools/plugin_packager.py
      displayName: "Packager script"

    - task: PublishPipelineArtifact@1
      displayName: "Publish artifact: plugin packaged"
      inputs:
        path: $(System.DefaultWorkingDirectory)/build/latest/isogeo_search_engine.zip
        artifact: "PACKAGED_$(Build.SourceBranchName)_$(Build.BuildId)"

- stage: DeployPackage
  # -- DEPLOY --------------------------------------------------------------------------
  displayName: "Deploy package"
  dependsOn:
    - Build
  condition: |
    and(
      succeeded(),
      contains(variables['Build.SourceBranch'], 'tags')
    )

  jobs:

  - job: 'PublishGithubRelease'
    displayName: "Publish to Github release"
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifactName: "PACKAGED_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)"

    - task: GitHubRelease@1
      continueOnError: true
      displayName: "Publish tagged code as Github Release"
      inputs:
        gitHubConnection: 'github.com_SimonSAMPERE'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        assets: "$(System.DefaultWorkingDirectory)/*"
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'

#####Upload pluginqgis to blobstorage######
  - job: 'UploadToBlobStorage'
    displayName: "Upload to Blob Storage (on premises)"
    pool:
      vmImage: $(vmImageName) 
    steps: 
    - checkout: none 
    - task: DownloadPipelineArtifact@2
      displayName: "Download artifact previously saved"
      inputs:
        buildType: "current"
        artifactName: "PACKAGED_$(Build.SourceBranchName)_$(Build.BuildId)"
        targetPath: "$(System.DefaultWorkingDirectory)" 
    - task: UsePythonVersion@0
      displayName: "Install Python"
      inputs:
        versionSpec: $(pythonVersion)
        architecture: "x64"
        addToPath: true 
    - script: python ./tools/plugin_packager.py
      displayName: "Packager script" 
    - script: copy 'build/latest/isogeo_search_engine.zip' '$(build.sourcesDirectory)/isogeo_search_engine-%$(VERSION_SUFIX)%.zip'
      displayName: Copy search engine into root
  
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
        scriptLocation: 'inlineScript'
        inlineScript: |
              az storage blob upload-batch -d isogeoonpremises -s $(build.sourcesDirectory) --pattern *.zip  --blob-endpoint https://isogeoonpremises.blob.core.windows.net  --sas-token '"$(AZURE_STORAGE_SAS_TOKEN)"' --account-key '"$(AZURE_STORAGE_KEY)"' --destination-path /plugin-qgis
  

## Update and overwrite to azure container versions.json file ##
- stage: Update_versions
  displayName: Update versions.json
  jobs:
  - job: Updatejson
    displayName: Update_version_json
    pool:
      vmImage: $(vmImageName)
    steps:

     - script: sudo apt-get install jq
       displayName: Install jq tools

     - task: AzureCLI@1
       inputs:
         azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
         scriptLocation: inlineScript
         inlineScript: |
             az storage blob download --account-name isogeoonpremises --container-name images --file versions.json --blob-url https://isogeoonpremises.blob.core.windows.net/images/isogeoonpremises/versions.json
       
     - script:   jq --argjson version "$(<version.json)" '.plugin-qgis |= . +  $version' versions.json > last.json
       displayName: first stage

     - script: cat last.json
       displayName: read versions.json
      
     - script: rm -rf versions.json && mv last.json versions.json
       displayName: read versions.json
       
     - task: AzureCLI@1
       inputs:
          azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
          scriptLocation: inlineScript
          inlineScript: |
               az storage blob upload-batch -d isogeoonpremises -s ./ --pattern versions.json  --blob-endpoint https://isogeoonpremises.blob.core.windows.net/images  --sas-token '"$(AZURE_STORAGE_SAS_TOKEN)"' --account-key '"$(AZURE_STORAGE_KEY)"'  --overwrite --destination-path /