# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isogeo_dockwidget_base.ui'
#
# Created: Fri Sep 02 11:20:51 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IsogeoDockWidgetBase(object):
    def setupUi(self, IsogeoDockWidgetBase):
        IsogeoDockWidgetBase.setObjectName(_fromUtf8("IsogeoDockWidgetBase"))
        IsogeoDockWidgetBase.resize(508, 866)
        IsogeoDockWidgetBase.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        IsogeoDockWidgetBase.setWindowTitle(_fromUtf8("Isogeo"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btn_report = QtGui.QPushButton(self.tab)
        self.btn_report.setObjectName(_fromUtf8("btn_report"))
        self.gridLayout_4.addWidget(self.btn_report, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 0, 4, 1, 1)
        self.txt_input = QtGui.QLineEdit(self.tab)
        self.txt_input.setInputMask(_fromUtf8(""))
        self.txt_input.setText(_fromUtf8(""))
        self.txt_input.setObjectName(_fromUtf8("txt_input"))
        self.gridLayout_4.addWidget(self.txt_input, 1, 0, 1, 2)
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.cbb_keywords = QtGui.QComboBox(self.widget)
        self.cbb_keywords.setGeometry(QtCore.QRect(10, 0, 211, 20))
        self.cbb_keywords.setObjectName(_fromUtf8("cbb_keywords"))
        self.gridLayout_4.addWidget(self.widget, 1, 2, 1, 3)
        self.grp_geofilter = QgsCollapsibleGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.grp_geofilter.setFont(font)
        self.grp_geofilter.setCollapsed(False)
        self.grp_geofilter.setObjectName(_fromUtf8("grp_geofilter"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grp_geofilter)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbb_operation = QtGui.QComboBox(self.grp_geofilter)
        self.cbb_operation.setObjectName(_fromUtf8("cbb_operation"))
        self.gridLayout_3.addWidget(self.cbb_operation, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.grp_geofilter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.grp_geofilter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_3.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.grp_geofilter, 2, 0, 1, 5)
        self.grp_filters = QgsCollapsibleGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.grp_filters.setFont(font)
        self.grp_filters.setCollapsed(False)
        self.grp_filters.setScrollOnExpand(True)
        self.grp_filters.setObjectName(_fromUtf8("grp_filters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grp_filters)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 2)
        self.cbb_format = QtGui.QComboBox(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_format.sizePolicy().hasHeightForWidth())
        self.cbb_format.setSizePolicy(sizePolicy)
        self.cbb_format.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_format.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cbb_format.setObjectName(_fromUtf8("cbb_format"))
        self.gridLayout_2.addWidget(self.cbb_format, 1, 0, 1, 3)
        self.cbb_owner = QtGui.QComboBox(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_owner.sizePolicy().hasHeightForWidth())
        self.cbb_owner.setSizePolicy(sizePolicy)
        self.cbb_owner.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_owner.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cbb_owner.setObjectName(_fromUtf8("cbb_owner"))
        self.gridLayout_2.addWidget(self.cbb_owner, 1, 3, 1, 3)
        self.label_4 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 3)
        self.cbb_inspire = QtGui.QComboBox(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_inspire.sizePolicy().hasHeightForWidth())
        self.cbb_inspire.setSizePolicy(sizePolicy)
        self.cbb_inspire.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_inspire.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cbb_inspire.setObjectName(_fromUtf8("cbb_inspire"))
        self.gridLayout_2.addWidget(self.cbb_inspire, 3, 0, 1, 3)
        self.cbb_srs = QtGui.QComboBox(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_srs.sizePolicy().hasHeightForWidth())
        self.cbb_srs.setSizePolicy(sizePolicy)
        self.cbb_srs.setMinimumSize(QtCore.QSize(30, 0))
        self.cbb_srs.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cbb_srs.setObjectName(_fromUtf8("cbb_srs"))
        self.gridLayout_2.addWidget(self.cbb_srs, 3, 3, 1, 3)
        self.label_24 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 4, 0, 1, 1)
        self.rdb_vector = QtGui.QRadioButton(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdb_vector.sizePolicy().hasHeightForWidth())
        self.rdb_vector.setSizePolicy(sizePolicy)
        self.rdb_vector.setObjectName(_fromUtf8("rdb_vector"))
        self.gridLayout_2.addWidget(self.rdb_vector, 4, 1, 1, 2)
        self.rdb_service = QtGui.QRadioButton(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdb_service.sizePolicy().hasHeightForWidth())
        self.rdb_service.setSizePolicy(sizePolicy)
        self.rdb_service.setObjectName(_fromUtf8("rdb_service"))
        self.gridLayout_2.addWidget(self.rdb_service, 4, 4, 1, 2)
        self.rdb_alltypes = QtGui.QRadioButton(self.grp_filters)
        self.rdb_alltypes.setObjectName(_fromUtf8("rdb_alltypes"))
        self.gridLayout_2.addWidget(self.rdb_alltypes, 5, 0, 1, 1)
        self.rdb_raster = QtGui.QRadioButton(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdb_raster.sizePolicy().hasHeightForWidth())
        self.rdb_raster.setSizePolicy(sizePolicy)
        self.rdb_raster.setObjectName(_fromUtf8("rdb_raster"))
        self.gridLayout_2.addWidget(self.rdb_raster, 5, 1, 1, 2)
        self.rdb_resource = QtGui.QRadioButton(self.grp_filters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdb_resource.sizePolicy().hasHeightForWidth())
        self.rdb_resource.setSizePolicy(sizePolicy)
        self.rdb_resource.setObjectName(_fromUtf8("rdb_resource"))
        self.gridLayout_2.addWidget(self.rdb_resource, 5, 4, 1, 2)
        self.label_6 = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 3)
        self.checkBox = QtGui.QCheckBox(self.grp_filters)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 7, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.grp_filters)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 7, 2, 1, 2)
        self.checkBox_3 = QtGui.QCheckBox(self.grp_filters)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 7, 4, 1, 2)
        self.label = QtGui.QLabel(self.grp_filters)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 8, 0, 1, 3)
        self.cbb_saved = QtGui.QComboBox(self.grp_filters)
        self.cbb_saved.setObjectName(_fromUtf8("cbb_saved"))
        self.gridLayout_2.addWidget(self.cbb_saved, 9, 0, 1, 3)
        self.btn_save = QtGui.QPushButton(self.grp_filters)
        self.btn_save.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/disc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.gridLayout_2.addWidget(self.btn_save, 9, 5, 1, 1)
        self.gridLayout_4.addWidget(self.grp_filters, 3, 0, 1, 5)
        self.btn_show = QtGui.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show.setIcon(icon1)
        self.btn_show.setObjectName(_fromUtf8("btn_show"))
        self.gridLayout_4.addWidget(self.btn_show, 4, 0, 1, 4)
        self.btn_reinit = QtGui.QPushButton(self.tab)
        self.btn_reinit.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reinit.setIcon(icon2)
        self.btn_reinit.setObjectName(_fromUtf8("btn_reinit"))
        self.gridLayout_4.addWidget(self.btn_reinit, 4, 4, 1, 1)
        self.tbl_result = QtGui.QTableWidget(self.tab)
        self.tbl_result.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbl_result.setObjectName(_fromUtf8("tbl_result"))
        self.tbl_result.setColumnCount(4)
        self.tbl_result.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_result.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_result.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_result.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_result.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tbl_result, 5, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 6, 0, 1, 1)
        self.btn_previous = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous.sizePolicy().hasHeightForWidth())
        self.btn_previous.setSizePolicy(sizePolicy)
        self.btn_previous.setText(_fromUtf8("<"))
        self.btn_previous.setObjectName(_fromUtf8("btn_previous"))
        self.gridLayout_4.addWidget(self.btn_previous, 6, 1, 1, 1)
        self.lbl_page = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_page.setFont(font)
        self.lbl_page.setObjectName(_fromUtf8("lbl_page"))
        self.gridLayout_4.addWidget(self.lbl_page, 6, 2, 1, 1)
        self.btn_next = QtGui.QPushButton(self.tab)
        self.btn_next.setObjectName(_fromUtf8("btn_next"))
        self.gridLayout_4.addWidget(self.btn_next, 6, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 6, 4, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 51))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.btn_change_user = QtGui.QPushButton(self.tab_2)
        self.btn_change_user.setObjectName(_fromUtf8("btn_change_user"))
        self.gridLayout_6.addWidget(self.btn_change_user, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.dump = QtGui.QLineEdit(self.groupBox)
        self.dump.setGeometry(QtCore.QRect(10, 40, 181, 20))
        self.dump.setObjectName(_fromUtf8("dump"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 60, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.default_ob = QtGui.QComboBox(self.groupBox_2)
        self.default_ob.setGeometry(QtCore.QRect(170, 60, 271, 22))
        self.default_ob.setObjectName(_fromUtf8("default_ob"))
        self.btn_default = QtGui.QPushButton(self.groupBox_2)
        self.btn_default.setGeometry(QtCore.QRect(340, 20, 101, 23))
        self.btn_default.setText(_fromUtf8(""))
        self.btn_default.setIcon(icon)
        self.btn_default.setObjectName(_fromUtf8("btn_default"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 311, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.groupBox_3, 3, 0, 1, 3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_6.addWidget(self.groupBox_4, 4, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem3, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 3)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 40, 231, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 40, 91, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.groupBox_5, 1, 0, 1, 4)
        self.resultats_2 = QtGui.QTableWidget(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resultats_2.setFont(font)
        self.resultats_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultats_2.setObjectName(_fromUtf8("resultats_2"))
        self.resultats_2.setColumnCount(4)
        self.resultats_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.resultats_2, 2, 0, 1, 4)
        self.nbresultat_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nbresultat_2.setFont(font)
        self.nbresultat_2.setObjectName(_fromUtf8("nbresultat_2"))
        self.gridLayout_5.addWidget(self.nbresultat_2, 3, 0, 1, 1)
        self.paging_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.paging_2.setFont(font)
        self.paging_2.setObjectName(_fromUtf8("paging_2"))
        self.gridLayout_5.addWidget(self.paging_2, 3, 1, 1, 1)
        self.previous_2 = QtGui.QPushButton(self.tab_3)
        self.previous_2.setObjectName(_fromUtf8("previous_2"))
        self.gridLayout_5.addWidget(self.previous_2, 3, 2, 1, 1)
        self.next_2 = QtGui.QPushButton(self.tab_3)
        self.next_2.setObjectName(_fromUtf8("next_2"))
        self.gridLayout_5.addWidget(self.next_2, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        IsogeoDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(IsogeoDockWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IsogeoDockWidgetBase)

    def retranslateUi(self, IsogeoDockWidgetBase):
        self.btn_report.setText(_translate("IsogeoDockWidgetBase", "Report an issue", None))
        self.grp_geofilter.setTitle(_translate("IsogeoDockWidgetBase", "Geographical filter", None))
        self.label_7.setText(_translate("IsogeoDockWidgetBase", "Operation", None))
        self.checkBox_4.setText(_translate("IsogeoDockWidgetBase", "Activate filter", None))
        self.grp_filters.setTitle(_translate("IsogeoDockWidgetBase", "Advanced search", None))
        self.label_2.setText(_translate("IsogeoDockWidgetBase", "Format", None))
        self.label_3.setText(_translate("IsogeoDockWidgetBase", "Owner", None))
        self.label_4.setText(_translate("IsogeoDockWidgetBase", "INSPIRE keywords", None))
        self.label_5.setText(_translate("IsogeoDockWidgetBase", "Coordinate system", None))
        self.label_24.setText(_translate("IsogeoDockWidgetBase", "Data type", None))
        self.rdb_vector.setText(_translate("IsogeoDockWidgetBase", "Vector dataset", None))
        self.rdb_service.setText(_translate("IsogeoDockWidgetBase", "Service", None))
        self.rdb_alltypes.setText(_translate("IsogeoDockWidgetBase", "Tous types", None))
        self.rdb_raster.setText(_translate("IsogeoDockWidgetBase", "Raster dataset", None))
        self.rdb_resource.setText(_translate("IsogeoDockWidgetBase", "Resource", None))
        self.label_6.setText(_translate("IsogeoDockWidgetBase", "Associated resources", None))
        self.checkBox.setText(_translate("IsogeoDockWidgetBase", "View", None))
        self.checkBox_2.setText(_translate("IsogeoDockWidgetBase", "Download", None))
        self.checkBox_3.setText(_translate("IsogeoDockWidgetBase", "Other actions", None))
        self.label.setText(_translate("IsogeoDockWidgetBase", "Saved researches", None))
        self.btn_show.setText(_translate("IsogeoDockWidgetBase", "Show results", None))
        self.tbl_result.setSortingEnabled(True)
        item = self.tbl_result.horizontalHeaderItem(0)
        item.setText(_translate("IsogeoDockWidgetBase", "Title", None))
        item = self.tbl_result.horizontalHeaderItem(1)
        item.setText(_translate("IsogeoDockWidgetBase", "Modified", None))
        item = self.tbl_result.horizontalHeaderItem(2)
        item.setText(_translate("IsogeoDockWidgetBase", "Type", None))
        item = self.tbl_result.horizontalHeaderItem(3)
        item.setText(_translate("IsogeoDockWidgetBase", "Add", None))
        self.lbl_page.setText(_translate("IsogeoDockWidgetBase", "Page x sur x", None))
        self.btn_next.setText(_translate("IsogeoDockWidgetBase", ">", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("IsogeoDockWidgetBase", "Search", None))
        self.label_10.setText(_translate("IsogeoDockWidgetBase", "Plugin set up", None))
        self.btn_change_user.setText(_translate("IsogeoDockWidgetBase", "Change user", None))
        self.groupBox.setTitle(_translate("IsogeoDockWidgetBase", "Isogeo administrator account", None))
        self.label_11.setText(_translate("IsogeoDockWidgetBase", "administrator id", None))
        self.label_12.setText(_translate("IsogeoDockWidgetBase", "Password", None))
        self.groupBox_2.setTitle(_translate("IsogeoDockWidgetBase", "Default research set up", None))
        self.label_15.setText(_translate("IsogeoDockWidgetBase", "Default results sorting", None))
        self.label_20.setText(_translate("IsogeoDockWidgetBase", "Save current research as default", None))
        self.groupBox_3.setTitle(_translate("IsogeoDockWidgetBase", "Saved researches parameters", None))
        self.label_16.setText(_translate("IsogeoDockWidgetBase", "Pick a research", None))
        self.pushButton.setText(_translate("IsogeoDockWidgetBase", "Rename", None))
        self.pushButton_2.setText(_translate("IsogeoDockWidgetBase", "Delete", None))
        self.groupBox_4.setTitle(_translate("IsogeoDockWidgetBase", "Lists parameters", None))
        self.label_17.setText(_translate("IsogeoDockWidgetBase", "Pick a list", None))
        self.pushButton_3.setText(_translate("IsogeoDockWidgetBase", "Rename", None))
        self.pushButton_4.setText(_translate("IsogeoDockWidgetBase", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("IsogeoDockWidgetBase", "Parameters", None))
        self.label_18.setText(_translate("IsogeoDockWidgetBase", "Isogeo metadata lists", None))
        self.groupBox_5.setTitle(_translate("IsogeoDockWidgetBase", "Custom list", None))
        self.label_19.setText(_translate("IsogeoDockWidgetBase", "Pick a list", None))
        self.pushButton_5.setText(_translate("IsogeoDockWidgetBase", "Create list", None))
        self.resultats_2.setSortingEnabled(True)
        item = self.resultats_2.horizontalHeaderItem(0)
        item.setText(_translate("IsogeoDockWidgetBase", "Titre", None))
        item = self.resultats_2.horizontalHeaderItem(1)
        item.setText(_translate("IsogeoDockWidgetBase", "Résumé", None))
        item = self.resultats_2.horizontalHeaderItem(2)
        item.setText(_translate("IsogeoDockWidgetBase", "Date de modif", None))
        item = self.resultats_2.horizontalHeaderItem(3)
        item.setText(_translate("IsogeoDockWidgetBase", "Ajouter", None))
        self.nbresultat_2.setText(_translate("IsogeoDockWidgetBase", "X metadata in the list", None))
        self.paging_2.setText(_translate("IsogeoDockWidgetBase", "Page 1 on 1", None))
        self.previous_2.setText(_translate("IsogeoDockWidgetBase", "<", None))
        self.next_2.setText(_translate("IsogeoDockWidgetBase", ">", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("IsogeoDockWidgetBase", "Lists", None))

from qgis.gui import QgsCollapsibleGroupBox
