# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isogeo_dockwidget_base.ui'
#
# Created: Thu Aug 04 17:12:32 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IsogeoDockWidgetBase(object):
    def setupUi(self, IsogeoDockWidgetBase):
        IsogeoDockWidgetBase.setObjectName(_fromUtf8("IsogeoDockWidgetBase"))
        IsogeoDockWidgetBase.resize(491, 866)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.report = QtGui.QPushButton(self.tab)
        self.report.setObjectName(_fromUtf8("report"))
        self.gridLayout_4.addWidget(self.report, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 0, 4, 1, 1)
        self.text_input = QtGui.QLineEdit(self.tab)
        self.text_input.setInputMask(_fromUtf8(""))
        self.text_input.setText(_fromUtf8(""))
        self.text_input.setObjectName(_fromUtf8("text_input"))
        self.gridLayout_4.addWidget(self.text_input, 1, 0, 1, 3)
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.keywords = QtGui.QComboBox(self.widget)
        self.keywords.setGeometry(QtCore.QRect(0, 0, 181, 20))
        self.keywords.setObjectName(_fromUtf8("keywords"))
        self.gridLayout_4.addWidget(self.widget, 1, 3, 1, 2)
        self.filters_box = QgsCollapsibleGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.filters_box.setFont(font)
        self.filters_box.setCollapsed(True)
        self.filters_box.setScrollOnExpand(True)
        self.filters_box.setObjectName(_fromUtf8("filters_box"))
        self.gridLayout_2 = QtGui.QGridLayout(self.filters_box)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.filters_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.filters_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.filters_box)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 6, 0, 1, 1)
        self.sys_coord = QtGui.QComboBox(self.filters_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_coord.sizePolicy().hasHeightForWidth())
        self.sys_coord.setSizePolicy(sizePolicy)
        self.sys_coord.setMinimumSize(QtCore.QSize(30, 0))
        self.sys_coord.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sys_coord.setObjectName(_fromUtf8("sys_coord"))
        self.gridLayout_2.addWidget(self.sys_coord, 4, 2, 1, 2)
        self.label_6 = QtGui.QLabel(self.filters_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 3)
        self.inspire = QtGui.QComboBox(self.filters_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inspire.sizePolicy().hasHeightForWidth())
        self.inspire.setSizePolicy(sizePolicy)
        self.inspire.setMinimumSize(QtCore.QSize(30, 0))
        self.inspire.setMaximumSize(QtCore.QSize(300, 16777215))
        self.inspire.setObjectName(_fromUtf8("inspire"))
        self.gridLayout_2.addWidget(self.inspire, 4, 0, 1, 2)
        self.checkBox_2 = QtGui.QCheckBox(self.filters_box)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 6, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.filters_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.filters_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.filters_box)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 6, 3, 1, 1)
        self.format = QtGui.QComboBox(self.filters_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format.sizePolicy().hasHeightForWidth())
        self.format.setSizePolicy(sizePolicy)
        self.format.setMinimumSize(QtCore.QSize(30, 0))
        self.format.setMaximumSize(QtCore.QSize(300, 16777215))
        self.format.setObjectName(_fromUtf8("format"))
        self.gridLayout_2.addWidget(self.format, 1, 0, 1, 2)
        self.owner = QtGui.QComboBox(self.filters_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owner.sizePolicy().hasHeightForWidth())
        self.owner.setSizePolicy(sizePolicy)
        self.owner.setMinimumSize(QtCore.QSize(30, 0))
        self.owner.setMaximumSize(QtCore.QSize(300, 16777215))
        self.owner.setObjectName(_fromUtf8("owner"))
        self.gridLayout_2.addWidget(self.owner, 1, 2, 1, 2)
        self.gridLayout_4.addWidget(self.filters_box, 2, 0, 1, 5)
        self.geofilter_box = QgsCollapsibleGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.geofilter_box.setFont(font)
        self.geofilter_box.setCollapsed(True)
        self.geofilter_box.setObjectName(_fromUtf8("geofilter_box"))
        self.gridLayout_3 = QtGui.QGridLayout(self.geofilter_box)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.operation = QtGui.QComboBox(self.geofilter_box)
        self.operation.setObjectName(_fromUtf8("operation"))
        self.gridLayout_3.addWidget(self.operation, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.geofilter_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.geofilter_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_3.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.geofilter_box, 3, 0, 1, 5)
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 4, 2, 1, 2)
        self.favorite_combo = QtGui.QComboBox(self.tab)
        self.favorite_combo.setObjectName(_fromUtf8("favorite_combo"))
        self.gridLayout_4.addWidget(self.favorite_combo, 5, 0, 1, 2)
        self.save_favorite = QtGui.QPushButton(self.tab)
        self.save_favorite.setObjectName(_fromUtf8("save_favorite"))
        self.gridLayout_4.addWidget(self.save_favorite, 5, 2, 1, 2)
        self.initialize = QtGui.QPushButton(self.tab)
        self.initialize.setObjectName(_fromUtf8("initialize"))
        self.gridLayout_4.addWidget(self.initialize, 5, 4, 1, 1)
        self.resultats = QtGui.QTableWidget(self.tab)
        self.resultats.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultats.setObjectName(_fromUtf8("resultats"))
        self.resultats.setColumnCount(4)
        self.resultats.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resultats.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultats.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultats.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resultats.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.resultats, 6, 0, 1, 5)
        self.nbresultat = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nbresultat.setFont(font)
        self.nbresultat.setObjectName(_fromUtf8("nbresultat"))
        self.gridLayout_4.addWidget(self.nbresultat, 7, 0, 1, 1)
        self.previous = QtGui.QPushButton(self.tab)
        self.previous.setObjectName(_fromUtf8("previous"))
        self.gridLayout_4.addWidget(self.previous, 7, 1, 1, 1)
        self.paging = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.paging.setFont(font)
        self.paging.setObjectName(_fromUtf8("paging"))
        self.gridLayout_4.addWidget(self.paging, 7, 2, 1, 1)
        self.next = QtGui.QPushButton(self.tab)
        self.next.setObjectName(_fromUtf8("next"))
        self.gridLayout_4.addWidget(self.next, 7, 3, 1, 1)
        self.show_button = QtGui.QPushButton(self.tab)
        self.show_button.setObjectName(_fromUtf8("show_button"))
        self.gridLayout_4.addWidget(self.show_button, 7, 4, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setMinimumSize(QtCore.QSize(0, 51))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.changeUser = QtGui.QPushButton(self.tab_2)
        self.changeUser.setObjectName(_fromUtf8("changeUser"))
        self.gridLayout_6.addWidget(self.changeUser, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.dump = QtGui.QLineEdit(self.groupBox)
        self.dump.setGeometry(QtCore.QRect(10, 40, 181, 20))
        self.dump.setObjectName(_fromUtf8("dump"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 60, 111, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_6.setGeometry(QtCore.QRect(130, 60, 141, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_7.setGeometry(QtCore.QRect(270, 60, 101, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 110, 181, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 160, 181, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_6.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_6.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 3)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 40, 231, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 40, 91, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.groupBox_5, 1, 0, 1, 4)
        self.resultats_2 = QtGui.QTableWidget(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resultats_2.setFont(font)
        self.resultats_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.resultats_2.setObjectName(_fromUtf8("resultats_2"))
        self.resultats_2.setColumnCount(4)
        self.resultats_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resultats_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.resultats_2, 2, 0, 1, 4)
        self.nbresultat_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nbresultat_2.setFont(font)
        self.nbresultat_2.setObjectName(_fromUtf8("nbresultat_2"))
        self.gridLayout_5.addWidget(self.nbresultat_2, 3, 0, 1, 1)
        self.paging_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.paging_2.setFont(font)
        self.paging_2.setObjectName(_fromUtf8("paging_2"))
        self.gridLayout_5.addWidget(self.paging_2, 3, 1, 1, 1)
        self.previous_2 = QtGui.QPushButton(self.tab_3)
        self.previous_2.setObjectName(_fromUtf8("previous_2"))
        self.gridLayout_5.addWidget(self.previous_2, 3, 2, 1, 1)
        self.next_2 = QtGui.QPushButton(self.tab_3)
        self.next_2.setObjectName(_fromUtf8("next_2"))
        self.gridLayout_5.addWidget(self.next_2, 3, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        IsogeoDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(IsogeoDockWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IsogeoDockWidgetBase)

    def retranslateUi(self, IsogeoDockWidgetBase):
        IsogeoDockWidgetBase.setWindowTitle(_translate("IsogeoDockWidgetBase", "Isogeo", None))
        self.report.setText(_translate("IsogeoDockWidgetBase", "Rapporter un problème", None))
        self.filters_box.setTitle(_translate("IsogeoDockWidgetBase", "Recherche avancée", None))
        self.label_3.setText(_translate("IsogeoDockWidgetBase", "Propriétaire", None))
        self.label_2.setText(_translate("IsogeoDockWidgetBase", "Format", None))
        self.checkBox.setText(_translate("IsogeoDockWidgetBase", "Visualisation", None))
        self.label_6.setText(_translate("IsogeoDockWidgetBase", "Ressources associées à la fiche", None))
        self.checkBox_2.setText(_translate("IsogeoDockWidgetBase", "Téléchargement", None))
        self.label_5.setText(_translate("IsogeoDockWidgetBase", "Système de coordonnées", None))
        self.label_4.setText(_translate("IsogeoDockWidgetBase", "Thématiques INSPIRE", None))
        self.checkBox_3.setText(_translate("IsogeoDockWidgetBase", "Autre action", None))
        self.geofilter_box.setTitle(_translate("IsogeoDockWidgetBase", "Filtre géographique", None))
        self.label_7.setText(_translate("IsogeoDockWidgetBase", "Opération", None))
        self.checkBox_4.setText(_translate("IsogeoDockWidgetBase", "Activer le filtre", None))
        self.label.setText(_translate("IsogeoDockWidgetBase", "Recherches enregistrées", None))
        self.label_9.setText(_translate("IsogeoDockWidgetBase", "Enregistrer", None))
        self.save_favorite.setText(_translate("IsogeoDockWidgetBase", "*", None))
        self.initialize.setText(_translate("IsogeoDockWidgetBase", "Réinitialiser", None))
        self.resultats.setSortingEnabled(True)
        item = self.resultats.horizontalHeaderItem(0)
        item.setText(_translate("IsogeoDockWidgetBase", "Titre", None))
        item = self.resultats.horizontalHeaderItem(1)
        item.setText(_translate("IsogeoDockWidgetBase", "Dernière modification", None))
        item = self.resultats.horizontalHeaderItem(2)
        item.setText(_translate("IsogeoDockWidgetBase", "Type de géométrie", None))
        item = self.resultats.horizontalHeaderItem(3)
        item.setText(_translate("IsogeoDockWidgetBase", "Ajouter", None))
        self.nbresultat.setText(_translate("IsogeoDockWidgetBase", "205 résultats", None))
        self.previous.setText(_translate("IsogeoDockWidgetBase", "<", None))
        self.paging.setText(_translate("IsogeoDockWidgetBase", "Page 1 sur 15", None))
        self.next.setText(_translate("IsogeoDockWidgetBase", ">", None))
        self.show_button.setText(_translate("IsogeoDockWidgetBase", "Afficher les résultats", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("IsogeoDockWidgetBase", "Recherche", None))
        self.label_10.setText(_translate("IsogeoDockWidgetBase", "Paramétrage du plugin", None))
        self.changeUser.setText(_translate("IsogeoDockWidgetBase", "Changer d\'utilisateur", None))
        self.groupBox.setTitle(_translate("IsogeoDockWidgetBase", "Compte administrateur Isogeo", None))
        self.label_11.setText(_translate("IsogeoDockWidgetBase", "id administrateur", None))
        self.label_12.setText(_translate("IsogeoDockWidgetBase", "Mot de passe", None))
        self.groupBox_2.setTitle(_translate("IsogeoDockWidgetBase", "Paramètres de recherche par défaut", None))
        self.checkBox_5.setText(_translate("IsogeoDockWidgetBase", "Données disponibles", None))
        self.checkBox_6.setText(_translate("IsogeoDockWidgetBase", "Données géographiques", None))
        self.checkBox_7.setText(_translate("IsogeoDockWidgetBase", "Toutes les fiches", None))
        self.label_13.setText(_translate("IsogeoDockWidgetBase", "Rechercher dans : ", None))
        self.label_14.setText(_translate("IsogeoDockWidgetBase", "Groupe de travail par défaut", None))
        self.label_15.setText(_translate("IsogeoDockWidgetBase", "Tri des résultats par défaut", None))
        self.groupBox_3.setTitle(_translate("IsogeoDockWidgetBase", "Gestions des recherches pré-enregistrées", None))
        self.label_16.setText(_translate("IsogeoDockWidgetBase", "Choisissez une recherche", None))
        self.pushButton.setText(_translate("IsogeoDockWidgetBase", "Renommer", None))
        self.pushButton_2.setText(_translate("IsogeoDockWidgetBase", "Supprimer", None))
        self.groupBox_4.setTitle(_translate("IsogeoDockWidgetBase", "Gestions des listes", None))
        self.label_17.setText(_translate("IsogeoDockWidgetBase", "Choisissez une liste", None))
        self.pushButton_3.setText(_translate("IsogeoDockWidgetBase", "Renommer", None))
        self.pushButton_4.setText(_translate("IsogeoDockWidgetBase", "Supprimer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("IsogeoDockWidgetBase", "Paramètres", None))
        self.label_18.setText(_translate("IsogeoDockWidgetBase", "Listes de fiches Isogeo", None))
        self.groupBox_5.setTitle(_translate("IsogeoDockWidgetBase", "Listes personnalisées", None))
        self.label_19.setText(_translate("IsogeoDockWidgetBase", "Choisissez une liste", None))
        self.pushButton_5.setText(_translate("IsogeoDockWidgetBase", "Créer une liste", None))
        self.resultats_2.setSortingEnabled(True)
        item = self.resultats_2.horizontalHeaderItem(0)
        item.setText(_translate("IsogeoDockWidgetBase", "Titre", None))
        item = self.resultats_2.horizontalHeaderItem(1)
        item.setText(_translate("IsogeoDockWidgetBase", "Résumé", None))
        item = self.resultats_2.horizontalHeaderItem(2)
        item.setText(_translate("IsogeoDockWidgetBase", "Date de modif", None))
        item = self.resultats_2.horizontalHeaderItem(3)
        item.setText(_translate("IsogeoDockWidgetBase", "Ajouter", None))
        self.nbresultat_2.setText(_translate("IsogeoDockWidgetBase", "12 fiches dans la liste", None))
        self.paging_2.setText(_translate("IsogeoDockWidgetBase", "Page 1 sur 1", None))
        self.previous_2.setText(_translate("IsogeoDockWidgetBase", "<", None))
        self.next_2.setText(_translate("IsogeoDockWidgetBase", ">", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("IsogeoDockWidgetBase", "Listes", None))

from qgis.gui import QgsCollapsibleGroupBox
