# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\metadata\ui_md_details.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlg_metadata_details(object):
    def setupUi(self, dlg_metadata_details):
        dlg_metadata_details.setObjectName("dlg_metadata_details")
        dlg_metadata_details.setWindowModality(QtCore.Qt.WindowModal)
        dlg_metadata_details.resize(800, 800)
        dlg_metadata_details.setMinimumSize(QtCore.QSize(800, 550))
        dlg_metadata_details.setMaximumSize(QtCore.QSize(16777215, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_metadata_details.setWindowIcon(icon)
        dlg_metadata_details.setWindowOpacity(1.0)
        dlg_metadata_details.setAutoFillBackground(True)
        dlg_metadata_details.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        dlg_metadata_details.setSizeGripEnabled(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(dlg_metadata_details)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.li_menu = QtWidgets.QListWidget(dlg_metadata_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.li_menu.sizePolicy().hasHeightForWidth())
        self.li_menu.setSizePolicy(sizePolicy)
        self.li_menu.setMinimumSize(QtCore.QSize(200, 500))
        self.li_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.li_menu.setFont(font)
        self.li_menu.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.li_menu.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.li_menu.setAutoFillBackground(True)
        self.li_menu.setStyleSheet("QListWidget{\n"
"    background-color: rgb(69, 69, 69, 220);\n"
"    outline: 0;\n"
"}\n"
"QListWidget::item {\n"
"    color: white;\n"
"    padding: 3px;\n"
"}\n"
"QListWidget::item::selected {\n"
"    color: black;\n"
"    background-color:palette(Window);\n"
"    padding-right: 0px;\n"
"}")
        self.li_menu.setFrameShape(QtWidgets.QFrame.Box)
        self.li_menu.setLineWidth(1)
        self.li_menu.setAlternatingRowColors(False)
        self.li_menu.setIconSize(QtCore.QSize(32, 32))
        self.li_menu.setMovement(QtWidgets.QListView.Static)
        self.li_menu.setViewMode(QtWidgets.QListView.ListMode)
        self.li_menu.setUniformItemSizes(True)
        self.li_menu.setWordWrap(True)
        self.li_menu.setSelectionRectVisible(True)
        self.li_menu.setObjectName("li_menu")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/bookmark_orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/list-alt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/phone_orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/calendar_orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/globe_orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/trophy_orange.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/gavel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.li_menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/code.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.li_menu.addItem(item)
        self.gridLayout_2.addWidget(self.li_menu, 0, 0, 1, 1)
        self.btn_md_edit = QtWidgets.QPushButton(dlg_metadata_details)
        self.btn_md_edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.btn_md_edit.setFont(font)
        self.btn_md_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_md_edit.setAutoFillBackground(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/pencil.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_md_edit.setIcon(icon9)
        self.btn_md_edit.setCheckable(False)
        self.btn_md_edit.setAutoRepeat(False)
        self.btn_md_edit.setAutoExclusive(False)
        self.btn_md_edit.setAutoDefault(False)
        self.btn_md_edit.setDefault(False)
        self.btn_md_edit.setFlat(False)
        self.btn_md_edit.setObjectName("btn_md_edit")
        self.gridLayout_2.addWidget(self.btn_md_edit, 1, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(dlg_metadata_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 800))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.md_general = QtWidgets.QWidget()
        self.md_general.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_general.setObjectName("md_general")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.md_general)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_title = QtWidgets.QLabel(self.md_general)
        self.lbl_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lbl_title.setText("")
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setWordWrap(True)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_11.addWidget(self.lbl_title)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ico_owner = QtWidgets.QLabel(self.md_general)
        self.ico_owner.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_owner.setMaximumSize(QtCore.QSize(20, 20))
        self.ico_owner.setText("")
        self.ico_owner.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/users_blue.svg"))
        self.ico_owner.setScaledContents(True)
        self.ico_owner.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_owner.setWordWrap(False)
        self.ico_owner.setObjectName("ico_owner")
        self.horizontalLayout_2.addWidget(self.ico_owner)
        self.val_owner = QtWidgets.QLabel(self.md_general)
        self.val_owner.setEnabled(True)
        self.val_owner.setMinimumSize(QtCore.QSize(0, 30))
        self.val_owner.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner.setFont(font)
        self.val_owner.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_owner.setAutoFillBackground(False)
        self.val_owner.setScaledContents(True)
        self.val_owner.setWordWrap(True)
        self.val_owner.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_owner.setObjectName("val_owner")
        self.horizontalLayout_2.addWidget(self.val_owner)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ico_group_themes = QtWidgets.QLabel(self.md_general)
        self.ico_group_themes.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_group_themes.setMaximumSize(QtCore.QSize(20, 20))
        self.ico_group_themes.setText("")
        self.ico_group_themes.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/paperclip.svg"))
        self.ico_group_themes.setScaledContents(True)
        self.ico_group_themes.setObjectName("ico_group_themes")
        self.horizontalLayout_3.addWidget(self.ico_group_themes)
        self.val_group_themes = QtWidgets.QLabel(self.md_general)
        self.val_group_themes.setMinimumSize(QtCore.QSize(100, 50))
        self.val_group_themes.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_group_themes.setFont(font)
        self.val_group_themes.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_group_themes.setScaledContents(True)
        self.val_group_themes.setWordWrap(True)
        self.val_group_themes.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_group_themes.setObjectName("val_group_themes")
        self.horizontalLayout_3.addWidget(self.val_group_themes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ico_keywords = QtWidgets.QLabel(self.md_general)
        self.ico_keywords.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_keywords.setMaximumSize(QtCore.QSize(20, 20))
        self.ico_keywords.setText("")
        self.ico_keywords.setTextFormat(QtCore.Qt.PlainText)
        self.ico_keywords.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/tag.svg"))
        self.ico_keywords.setScaledContents(True)
        self.ico_keywords.setWordWrap(False)
        self.ico_keywords.setObjectName("ico_keywords")
        self.horizontalLayout_4.addWidget(self.ico_keywords)
        self.val_keywords = QtWidgets.QLabel(self.md_general)
        self.val_keywords.setMinimumSize(QtCore.QSize(100, 50))
        self.val_keywords.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_keywords.setFont(font)
        self.val_keywords.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_keywords.setAutoFillBackground(False)
        self.val_keywords.setScaledContents(True)
        self.val_keywords.setWordWrap(True)
        self.val_keywords.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_keywords.setObjectName("val_keywords")
        self.horizontalLayout_4.addWidget(self.val_keywords)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ico_inspire_themes = QtWidgets.QLabel(self.md_general)
        self.ico_inspire_themes.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_inspire_themes.setMaximumSize(QtCore.QSize(20, 20))
        self.ico_inspire_themes.setAutoFillBackground(True)
        self.ico_inspire_themes.setText("")
        self.ico_inspire_themes.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/leaf.svg"))
        self.ico_inspire_themes.setScaledContents(True)
        self.ico_inspire_themes.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_inspire_themes.setObjectName("ico_inspire_themes")
        self.horizontalLayout_5.addWidget(self.ico_inspire_themes)
        self.val_inspire_themes = QtWidgets.QLabel(self.md_general)
        self.val_inspire_themes.setMinimumSize(QtCore.QSize(100, 50))
        self.val_inspire_themes.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_inspire_themes.setFont(font)
        self.val_inspire_themes.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_inspire_themes.setAutoFillBackground(False)
        self.val_inspire_themes.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_inspire_themes.setObjectName("val_inspire_themes")
        self.horizontalLayout_5.addWidget(self.val_inspire_themes)
        self.ico_inspire_conformity = QtWidgets.QLabel(self.md_general)
        self.ico_inspire_conformity.setEnabled(False)
        self.ico_inspire_conformity.setMaximumSize(QtCore.QSize(32, 32))
        self.ico_inspire_conformity.setAutoFillBackground(True)
        self.ico_inspire_conformity.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ico_inspire_conformity.setText("")
        self.ico_inspire_conformity.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/inspire.png"))
        self.ico_inspire_conformity.setScaledContents(True)
        self.ico_inspire_conformity.setWordWrap(True)
        self.ico_inspire_conformity.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_inspire_conformity.setObjectName("ico_inspire_conformity")
        self.horizontalLayout_5.addWidget(self.ico_inspire_conformity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.ico_abstract = QtWidgets.QLabel(self.md_general)
        self.ico_abstract.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_abstract.setMaximumSize(QtCore.QSize(20, 20))
        self.ico_abstract.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ico_abstract.setText("")
        self.ico_abstract.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/bookmark_blue.svg"))
        self.ico_abstract.setScaledContents(True)
        self.ico_abstract.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ico_abstract.setWordWrap(False)
        self.ico_abstract.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_abstract.setObjectName("ico_abstract")
        self.gridLayout_14.addWidget(self.ico_abstract, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.md_general)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(110, 200))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_abstract = QtWidgets.QWidget()
        self.scroll_abstract.setGeometry(QtCore.QRect(0, 0, 514, 198))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_abstract.sizePolicy().hasHeightForWidth())
        self.scroll_abstract.setSizePolicy(sizePolicy)
        self.scroll_abstract.setMinimumSize(QtCore.QSize(110, 0))
        self.scroll_abstract.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scroll_abstract.setObjectName("scroll_abstract")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.scroll_abstract)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.val_abstract = QtWidgets.QLabel(self.scroll_abstract)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.val_abstract.sizePolicy().hasHeightForWidth())
        self.val_abstract.setSizePolicy(sizePolicy)
        self.val_abstract.setMinimumSize(QtCore.QSize(100, 0))
        self.val_abstract.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_abstract.setFont(font)
        self.val_abstract.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_abstract.setAutoFillBackground(False)
        self.val_abstract.setScaledContents(True)
        self.val_abstract.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_abstract.setWordWrap(True)
        self.val_abstract.setOpenExternalLinks(True)
        self.val_abstract.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_abstract.setObjectName("val_abstract")
        self.gridLayout_17.addWidget(self.val_abstract, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scroll_abstract)
        self.gridLayout_14.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(1, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.stackedWidget.addWidget(self.md_general)
        self.md_feat_attributes = QtWidgets.QWidget()
        self.md_feat_attributes.setMinimumSize(QtCore.QSize(0, 0))
        self.md_feat_attributes.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_feat_attributes.setObjectName("md_feat_attributes")
        self.gridLayout = QtWidgets.QGridLayout(self.md_feat_attributes)
        self.gridLayout.setObjectName("gridLayout")
        self.tbl_attributes = QtWidgets.QTableWidget(self.md_feat_attributes)
        self.tbl_attributes.setMinimumSize(QtCore.QSize(200, 250))
        self.tbl_attributes.setMaximumSize(QtCore.QSize(16777215, 700))
        self.tbl_attributes.setAutoFillBackground(True)
        self.tbl_attributes.setTabKeyNavigation(True)
        self.tbl_attributes.setProperty("showDropIndicator", False)
        self.tbl_attributes.setDragDropOverwriteMode(False)
        self.tbl_attributes.setAlternatingRowColors(True)
        self.tbl_attributes.setObjectName("tbl_attributes")
        self.tbl_attributes.setColumnCount(4)
        self.tbl_attributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(3, item)
        self.tbl_attributes.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tbl_attributes, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.md_feat_attributes)
        self.md_contacts = QtWidgets.QWidget()
        self.md_contacts.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_contacts.setObjectName("md_contacts")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.md_contacts)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grp_pointof = QtWidgets.QGroupBox(self.md_contacts)
        self.grp_pointof.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_pointof.setFont(font)
        self.grp_pointof.setObjectName("grp_pointof")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.grp_pointof)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scroll_ct_pointof = QtWidgets.QScrollArea(self.grp_pointof)
        self.scroll_ct_pointof.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.scroll_ct_pointof.setFont(font)
        self.scroll_ct_pointof.setWidgetResizable(True)
        self.scroll_ct_pointof.setObjectName("scroll_ct_pointof")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 521, 194))
        self.scrollAreaWidgetContents_3.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.val_ct_pointof = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.val_ct_pointof.setMinimumSize(QtCore.QSize(0, 150))
        self.val_ct_pointof.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_ct_pointof.setFont(font)
        self.val_ct_pointof.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_ct_pointof.setAutoFillBackground(False)
        self.val_ct_pointof.setScaledContents(True)
        self.val_ct_pointof.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_ct_pointof.setOpenExternalLinks(True)
        self.val_ct_pointof.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_ct_pointof.setObjectName("val_ct_pointof")
        self.gridLayout_16.addWidget(self.val_ct_pointof, 0, 0, 1, 1)
        self.scroll_ct_pointof.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.addWidget(self.scroll_ct_pointof, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.grp_pointof, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.md_contacts)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.scroll_ct_other = QtWidgets.QScrollArea(self.groupBox)
        self.scroll_ct_other.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scroll_ct_other.setWidgetResizable(True)
        self.scroll_ct_other.setObjectName("scroll_ct_other")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 521, 195))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.val_ct_other = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.val_ct_other.setMinimumSize(QtCore.QSize(0, 150))
        self.val_ct_other.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_ct_other.setFont(font)
        self.val_ct_other.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_ct_other.setToolTip("")
        self.val_ct_other.setAutoFillBackground(False)
        self.val_ct_other.setScaledContents(True)
        self.val_ct_other.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_ct_other.setWordWrap(True)
        self.val_ct_other.setOpenExternalLinks(True)
        self.val_ct_other.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_ct_other.setObjectName("val_ct_other")
        self.gridLayout_15.addWidget(self.val_ct_other, 0, 0, 1, 1)
        self.scroll_ct_other.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_13.addWidget(self.scroll_ct_other, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.md_contacts)
        self.md_history = QtWidgets.QWidget()
        self.md_history.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_history.setObjectName("md_history")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.md_history)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.grp_history = QtWidgets.QGroupBox(self.md_history)
        self.grp_history.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_history.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_history.setFont(font)
        self.grp_history.setObjectName("grp_history")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grp_history)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vert_separator = QtWidgets.QFrame(self.grp_history)
        self.vert_separator.setFrameShape(QtWidgets.QFrame.VLine)
        self.vert_separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vert_separator.setObjectName("vert_separator")
        self.gridLayout_5.addWidget(self.vert_separator, 0, 1, 3, 2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.val_frequency = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_frequency.setFont(font)
        self.val_frequency.setObjectName("val_frequency")
        self.gridLayout_9.addWidget(self.val_frequency, 2, 5, 1, 1)
        self.lbl_frequency = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_frequency.setFont(font)
        self.lbl_frequency.setObjectName("lbl_frequency")
        self.gridLayout_9.addWidget(self.lbl_frequency, 2, 2, 1, 1)
        self.val_data_update = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_data_update.setFont(font)
        self.val_data_update.setObjectName("val_data_update")
        self.gridLayout_9.addWidget(self.val_data_update, 1, 5, 1, 1)
        self.lbl_data_update = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_data_update.setFont(font)
        self.lbl_data_update.setObjectName("lbl_data_update")
        self.gridLayout_9.addWidget(self.lbl_data_update, 1, 2, 1, 1)
        self.ico_data_update = QtWidgets.QLabel(self.grp_history)
        self.ico_data_update.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_data_update.setText("")
        self.ico_data_update.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/results/sort-datamodified.svg"))
        self.ico_data_update.setScaledContents(True)
        self.ico_data_update.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_data_update.setObjectName("ico_data_update")
        self.gridLayout_9.addWidget(self.ico_data_update, 1, 1, 1, 1)
        self.val_data_crea = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_data_crea.setFont(font)
        self.val_data_crea.setObjectName("val_data_crea")
        self.gridLayout_9.addWidget(self.val_data_crea, 0, 5, 1, 1)
        self.ico_data_crea = QtWidgets.QLabel(self.grp_history)
        self.ico_data_crea.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_data_crea.setText("")
        self.ico_data_crea.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/results/sort-datacreated.svg"))
        self.ico_data_crea.setScaledContents(True)
        self.ico_data_crea.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_data_crea.setObjectName("ico_data_crea")
        self.gridLayout_9.addWidget(self.ico_data_crea, 0, 1, 1, 1)
        self.lbl_data_crea = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_data_crea.setFont(font)
        self.lbl_data_crea.setObjectName("lbl_data_crea")
        self.gridLayout_9.addWidget(self.lbl_data_crea, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 2, 3, 1, 1)
        self.ico_frequency = QtWidgets.QLabel(self.grp_history)
        self.ico_frequency.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ico_frequency.setFont(font)
        self.ico_frequency.setText("")
        self.ico_frequency.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/refresh.svg"))
        self.ico_frequency.setScaledContents(True)
        self.ico_frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_frequency.setObjectName("ico_frequency")
        self.gridLayout_9.addWidget(self.ico_frequency, 2, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_9)
        self.gridLayout_5.addLayout(self.verticalLayout_14, 1, 0, 2, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lbl_valid_comment = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_valid_comment.setFont(font)
        self.lbl_valid_comment.setObjectName("lbl_valid_comment")
        self.gridLayout_11.addWidget(self.lbl_valid_comment, 2, 1, 1, 1)
        self.val_valid_comment = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_valid_comment.setFont(font)
        self.val_valid_comment.setScaledContents(True)
        self.val_valid_comment.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.val_valid_comment.setWordWrap(True)
        self.val_valid_comment.setOpenExternalLinks(True)
        self.val_valid_comment.setObjectName("val_valid_comment")
        self.gridLayout_11.addWidget(self.val_valid_comment, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 2, 2, 1, 1)
        self.ico_valid_comment = QtWidgets.QLabel(self.grp_history)
        self.ico_valid_comment.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ico_valid_comment.setFont(font)
        self.ico_valid_comment.setAutoFillBackground(True)
        self.ico_valid_comment.setText("")
        self.ico_valid_comment.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/comment-o.svg"))
        self.ico_valid_comment.setScaledContents(True)
        self.ico_valid_comment.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_valid_comment.setWordWrap(True)
        self.ico_valid_comment.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_valid_comment.setObjectName("ico_valid_comment")
        self.gridLayout_11.addWidget(self.ico_valid_comment, 2, 0, 1, 1)
        self.ico_valid_end = QtWidgets.QLabel(self.grp_history)
        self.ico_valid_end.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_valid_end.setText("")
        self.ico_valid_end.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/calendar-times-o.svg"))
        self.ico_valid_end.setScaledContents(True)
        self.ico_valid_end.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_valid_end.setObjectName("ico_valid_end")
        self.gridLayout_11.addWidget(self.ico_valid_end, 1, 0, 1, 1)
        self.val_valid_end = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_valid_end.setFont(font)
        self.val_valid_end.setObjectName("val_valid_end")
        self.gridLayout_11.addWidget(self.val_valid_end, 1, 3, 1, 1)
        self.ico_valid_start = QtWidgets.QLabel(self.grp_history)
        self.ico_valid_start.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_valid_start.setText("")
        self.ico_valid_start.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/calendar-check-o.svg"))
        self.ico_valid_start.setScaledContents(True)
        self.ico_valid_start.setAlignment(QtCore.Qt.AlignCenter)
        self.ico_valid_start.setObjectName("ico_valid_start")
        self.gridLayout_11.addWidget(self.ico_valid_start, 0, 0, 1, 1)
        self.lbl_valid_start = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_valid_start.setFont(font)
        self.lbl_valid_start.setObjectName("lbl_valid_start")
        self.gridLayout_11.addWidget(self.lbl_valid_start, 0, 1, 1, 1)
        self.val_valid_start = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_valid_start.setFont(font)
        self.val_valid_start.setObjectName("val_valid_start")
        self.gridLayout_11.addWidget(self.val_valid_start, 0, 3, 1, 1)
        self.lbl_valid_end = QtWidgets.QLabel(self.grp_history)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_valid_end.setFont(font)
        self.lbl_valid_end.setObjectName("lbl_valid_end")
        self.gridLayout_11.addWidget(self.lbl_valid_end, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem7, 0, 2, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_11)
        self.gridLayout_5.addLayout(self.verticalLayout_15, 1, 2, 2, 1)
        self.vert_separator.raise_()
        self.verticalLayout_18.addWidget(self.grp_history)
        self.grp_collect_context = QtWidgets.QGroupBox(self.md_history)
        self.grp_collect_context.setMinimumSize(QtCore.QSize(0, 110))
        self.grp_collect_context.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_collect_context.setFont(font)
        self.grp_collect_context.setObjectName("grp_collect_context")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grp_collect_context)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.grp_collect_context)
        self.scrollArea_7.setMinimumSize(QtCore.QSize(0, 110))
        self.scrollArea_7.setMaximumSize(QtCore.QSize(16777215, 140))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 521, 108))
        self.scrollAreaWidgetContents_8.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollAreaWidgetContents_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_8)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.val_context = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.val_context.setMinimumSize(QtCore.QSize(0, 50))
        self.val_context.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_context.setFont(font)
        self.val_context.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_context.setAutoFillBackground(False)
        self.val_context.setScaledContents(True)
        self.val_context.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_context.setWordWrap(True)
        self.val_context.setOpenExternalLinks(True)
        self.val_context.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_context.setObjectName("val_context")
        self.gridLayout_30.addWidget(self.val_context, 0, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_6.addWidget(self.scrollArea_7)
        self.verticalLayout_18.addWidget(self.grp_collect_context)
        self.grp_collect_method = QtWidgets.QGroupBox(self.md_history)
        self.grp_collect_method.setMinimumSize(QtCore.QSize(0, 110))
        self.grp_collect_method.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_collect_method.setFont(font)
        self.grp_collect_method.setObjectName("grp_collect_method")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grp_collect_method)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_9 = QtWidgets.QScrollArea(self.grp_collect_method)
        self.scrollArea_9.setMinimumSize(QtCore.QSize(0, 110))
        self.scrollArea_9.setMaximumSize(QtCore.QSize(16777215, 140))
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 521, 108))
        self.scrollAreaWidgetContents_10.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.val_method = QtWidgets.QLabel(self.scrollAreaWidgetContents_10)
        self.val_method.setMinimumSize(QtCore.QSize(0, 50))
        self.val_method.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_method.setFont(font)
        self.val_method.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_method.setAutoFillBackground(False)
        self.val_method.setScaledContents(True)
        self.val_method.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_method.setWordWrap(True)
        self.val_method.setOpenExternalLinks(True)
        self.val_method.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_method.setObjectName("val_method")
        self.gridLayout_4.addWidget(self.val_method, 0, 0, 1, 1)
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_10)
        self.verticalLayout_7.addWidget(self.scrollArea_9)
        self.verticalLayout_18.addWidget(self.grp_collect_method)
        self.mGroupBox = QgsCollapsibleGroupBox(self.md_history)
        self.mGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.mGroupBox.setFont(font)
        self.mGroupBox.setCollapsed(False)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tbl_events = QtWidgets.QTableWidget(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_events.sizePolicy().hasHeightForWidth())
        self.tbl_events.setSizePolicy(sizePolicy)
        self.tbl_events.setMinimumSize(QtCore.QSize(150, 50))
        self.tbl_events.setMaximumSize(QtCore.QSize(16777215, 440))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.tbl_events.setFont(font)
        self.tbl_events.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.tbl_events.setAutoFillBackground(True)
        self.tbl_events.setProperty("showDropIndicator", False)
        self.tbl_events.setDragDropOverwriteMode(False)
        self.tbl_events.setAlternatingRowColors(True)
        self.tbl_events.setObjectName("tbl_events")
        self.tbl_events.setColumnCount(2)
        self.tbl_events.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignBottom)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/calendar-o.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.tbl_events.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.tbl_events.setHorizontalHeaderItem(1, item)
        self.tbl_events.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tbl_events)
        self.verticalLayout_18.addWidget(self.mGroupBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.md_history)
        self.md_geography = QtWidgets.QWidget()
        self.md_geography.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_geography.setObjectName("md_geography")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.md_geography)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.grp_technic = QtWidgets.QGroupBox(self.md_geography)
        self.grp_technic.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_technic.setFont(font)
        self.grp_technic.setAutoFillBackground(False)
        self.grp_technic.setObjectName("grp_technic")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.grp_technic)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line = QtWidgets.QFrame(self.grp_technic)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.ico_format = QtWidgets.QLabel(self.grp_technic)
        self.ico_format.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_format.setText("")
        self.ico_format.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/cube_blue.svg"))
        self.ico_format.setScaledContents(True)
        self.ico_format.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_format.setObjectName("ico_format")
        self.gridLayout_20.addWidget(self.ico_format, 0, 0, 1, 1)
        self.val_format = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_format.setFont(font)
        self.val_format.setObjectName("val_format")
        self.gridLayout_20.addWidget(self.val_format, 0, 3, 1, 1)
        self.lbl_format = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_format.setFont(font)
        self.lbl_format.setObjectName("lbl_format")
        self.gridLayout_20.addWidget(self.lbl_format, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem9, 0, 2, 1, 1)
        self.ico_feat_count = QtWidgets.QLabel(self.grp_technic)
        self.ico_feat_count.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_feat_count.setText("")
        self.ico_feat_count.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/cubes.svg"))
        self.ico_feat_count.setScaledContents(True)
        self.ico_feat_count.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_feat_count.setObjectName("ico_feat_count")
        self.gridLayout_20.addWidget(self.ico_feat_count, 1, 0, 1, 1)
        self.lbl_feat_count = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_feat_count.setFont(font)
        self.lbl_feat_count.setObjectName("lbl_feat_count")
        self.gridLayout_20.addWidget(self.lbl_feat_count, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem10, 1, 2, 1, 1)
        self.val_feat_count = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_feat_count.setFont(font)
        self.val_feat_count.setObjectName("val_feat_count")
        self.gridLayout_20.addWidget(self.val_feat_count, 1, 3, 1, 1)
        self.lbl_geometry = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_geometry.setFont(font)
        self.lbl_geometry.setObjectName("lbl_geometry")
        self.gridLayout_20.addWidget(self.lbl_geometry, 2, 1, 1, 1)
        self.ico_geometry = QtWidgets.QLabel(self.grp_technic)
        self.ico_geometry.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_geometry.setText("")
        self.ico_geometry.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/multi.svg"))
        self.ico_geometry.setScaledContents(True)
        self.ico_geometry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_geometry.setObjectName("ico_geometry")
        self.gridLayout_20.addWidget(self.ico_geometry, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem11, 2, 2, 1, 1)
        self.val_geometry = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_geometry.setFont(font)
        self.val_geometry.setObjectName("val_geometry")
        self.gridLayout_20.addWidget(self.val_geometry, 2, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.ico_scale = QtWidgets.QLabel(self.grp_technic)
        self.ico_scale.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_scale.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_scale.setAutoFillBackground(True)
        self.ico_scale.setText("")
        self.ico_scale.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/arrows-h.svg"))
        self.ico_scale.setScaledContents(True)
        self.ico_scale.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_scale.setObjectName("ico_scale")
        self.gridLayout_19.addWidget(self.ico_scale, 1, 0, 1, 1)
        self.val_scale = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_scale.setFont(font)
        self.val_scale.setObjectName("val_scale")
        self.gridLayout_19.addWidget(self.val_scale, 1, 3, 1, 1)
        self.ico_srs = QtWidgets.QLabel(self.grp_technic)
        self.ico_srs.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_srs.setText("")
        self.ico_srs.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/compass.svg"))
        self.ico_srs.setScaledContents(True)
        self.ico_srs.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_srs.setObjectName("ico_srs")
        self.gridLayout_19.addWidget(self.ico_srs, 0, 0, 1, 1)
        self.lbl_scale = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_scale.setFont(font)
        self.lbl_scale.setObjectName("lbl_scale")
        self.gridLayout_19.addWidget(self.lbl_scale, 1, 1, 1, 1)
        self.lbl_srs = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_srs.setFont(font)
        self.lbl_srs.setObjectName("lbl_srs")
        self.gridLayout_19.addWidget(self.lbl_srs, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem12, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem13, 1, 2, 1, 1)
        self.val_srs = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_srs.setFont(font)
        self.val_srs.setObjectName("val_srs")
        self.gridLayout_19.addWidget(self.val_srs, 0, 3, 1, 1)
        self.ico_resolution = QtWidgets.QLabel(self.grp_technic)
        self.ico_resolution.setMaximumSize(QtCore.QSize(16, 16))
        self.ico_resolution.setAutoFillBackground(True)
        self.ico_resolution.setText("")
        self.ico_resolution.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/th.svg"))
        self.ico_resolution.setScaledContents(True)
        self.ico_resolution.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ico_resolution.setObjectName("ico_resolution")
        self.gridLayout_19.addWidget(self.ico_resolution, 2, 0, 1, 1)
        self.lbl_resolution = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_resolution.setFont(font)
        self.lbl_resolution.setObjectName("lbl_resolution")
        self.gridLayout_19.addWidget(self.lbl_resolution, 2, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem14, 2, 2, 1, 1)
        self.val_resolution = QtWidgets.QLabel(self.grp_technic)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_resolution.setFont(font)
        self.val_resolution.setObjectName("val_resolution")
        self.gridLayout_19.addWidget(self.val_resolution, 2, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_19, 0, 2, 1, 1)
        self.verticalLayout_22.addWidget(self.grp_technic)
        self.grp_geoContext = QtWidgets.QGroupBox(self.md_geography)
        self.grp_geoContext.setMinimumSize(QtCore.QSize(0, 100))
        self.grp_geoContext.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_geoContext.setFont(font)
        self.grp_geoContext.setObjectName("grp_geoContext")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grp_geoContext)
        self.verticalLayout.setObjectName("verticalLayout")
        self.val_geoContext = QtWidgets.QLabel(self.grp_geoContext)
        self.val_geoContext.setMinimumSize(QtCore.QSize(0, 100))
        self.val_geoContext.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_geoContext.setFont(font)
        self.val_geoContext.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_geoContext.setAutoFillBackground(False)
        self.val_geoContext.setScaledContents(True)
        self.val_geoContext.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_geoContext.setWordWrap(True)
        self.val_geoContext.setOpenExternalLinks(True)
        self.val_geoContext.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_geoContext.setObjectName("val_geoContext")
        self.verticalLayout.addWidget(self.val_geoContext)
        self.verticalLayout_22.addWidget(self.grp_geoContext)
        self.grp_bbox = QtWidgets.QGroupBox(self.md_geography)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_bbox.sizePolicy().hasHeightForWidth())
        self.grp_bbox.setSizePolicy(sizePolicy)
        self.grp_bbox.setMinimumSize(QtCore.QSize(0, 150))
        self.grp_bbox.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_bbox.setFont(font)
        self.grp_bbox.setAutoFillBackground(False)
        self.grp_bbox.setFlat(False)
        self.grp_bbox.setObjectName("grp_bbox")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.grp_bbox)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.wid_bbox = QgsMapCanvas(self.grp_bbox)
        self.wid_bbox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_bbox.sizePolicy().hasHeightForWidth())
        self.wid_bbox.setSizePolicy(sizePolicy)
        self.wid_bbox.setMinimumSize(QtCore.QSize(200, 200))
        self.wid_bbox.setMaximumSize(QtCore.QSize(16777215, 380))
        self.wid_bbox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.wid_bbox.setObjectName("wid_bbox")
        self.gridLayout_18.addWidget(self.wid_bbox, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.grp_bbox)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem15)
        self.stackedWidget.addWidget(self.md_geography)
        self.md_quality = QtWidgets.QWidget()
        self.md_quality.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_quality.setObjectName("md_quality")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.md_quality)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.grp_specification = QtWidgets.QGroupBox(self.md_quality)
        self.grp_specification.setMinimumSize(QtCore.QSize(0, 100))
        self.grp_specification.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_specification.setFont(font)
        self.grp_specification.setAutoFillBackground(False)
        self.grp_specification.setObjectName("grp_specification")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.grp_specification)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.grp_specification)
        self.scrollArea_5.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 521, 194))
        self.scrollAreaWidgetContents_6.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.val_specifications = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.val_specifications.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_specifications.setFont(font)
        self.val_specifications.setAutoFillBackground(False)
        self.val_specifications.setScaledContents(True)
        self.val_specifications.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_specifications.setWordWrap(True)
        self.val_specifications.setOpenExternalLinks(True)
        self.val_specifications.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_specifications.setObjectName("val_specifications")
        self.gridLayout_28.addWidget(self.val_specifications, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_22.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.grp_specification)
        self.grp_topoConsist = QtWidgets.QGroupBox(self.md_quality)
        self.grp_topoConsist.setMinimumSize(QtCore.QSize(0, 70))
        self.grp_topoConsist.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_topoConsist.setFont(font)
        self.grp_topoConsist.setObjectName("grp_topoConsist")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.grp_topoConsist)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.grp_topoConsist)
        self.scrollArea_6.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 521, 195))
        self.scrollAreaWidgetContents_7.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.val_topology = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.val_topology.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_topology.setFont(font)
        self.val_topology.setAutoFillBackground(False)
        self.val_topology.setScaledContents(True)
        self.val_topology.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_topology.setWordWrap(True)
        self.val_topology.setOpenExternalLinks(True)
        self.val_topology.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_topology.setObjectName("val_topology")
        self.gridLayout_29.addWidget(self.val_topology, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_27.addWidget(self.scrollArea_6, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.grp_topoConsist)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.md_quality)
        self.md_cgu = QtWidgets.QWidget()
        self.md_cgu.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_cgu.setObjectName("md_cgu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.md_cgu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grp_licences = QtWidgets.QGroupBox(self.md_cgu)
        self.grp_licences.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_licences.setFont(font)
        self.grp_licences.setAutoFillBackground(False)
        self.grp_licences.setObjectName("grp_licences")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.grp_licences)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.grp_licences)
        self.scrollArea_3.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 521, 194))
        self.scrollAreaWidgetContents_4.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.val_licenses = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.val_licenses.setMinimumSize(QtCore.QSize(0, 150))
        self.val_licenses.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_licenses.setFont(font)
        self.val_licenses.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_licenses.setAutoFillBackground(False)
        self.val_licenses.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_licenses.setWordWrap(True)
        self.val_licenses.setOpenExternalLinks(True)
        self.val_licenses.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_licenses.setObjectName("val_licenses")
        self.gridLayout_26.addWidget(self.val_licenses, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_23.addWidget(self.scrollArea_3, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.grp_licences)
        self.groupBox_2 = QtWidgets.QGroupBox(self.md_cgu)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_4.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 521, 195))
        self.scrollAreaWidgetContents_5.setMaximumSize(QtCore.QSize(16777215, 350))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.val_limitations = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.val_limitations.setMinimumSize(QtCore.QSize(0, 150))
        self.val_limitations.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_limitations.setFont(font)
        self.val_limitations.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.val_limitations.setAutoFillBackground(False)
        self.val_limitations.setScaledContents(True)
        self.val_limitations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.val_limitations.setWordWrap(True)
        self.val_limitations.setOpenExternalLinks(True)
        self.val_limitations.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.val_limitations.setObjectName("val_limitations")
        self.gridLayout_25.addWidget(self.val_limitations, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_24.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.md_cgu)
        self.md_advanced = QtWidgets.QWidget()
        self.md_advanced.setMaximumSize(QtCore.QSize(16777215, 739))
        self.md_advanced.setObjectName("md_advanced")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.md_advanced)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.md_advanced)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 739))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 545, 715))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 739))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 3, 0, 1, 2)
        self.btn_xml_dl = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_xml_dl.setIcon(icon12)
        self.btn_xml_dl.setDefault(True)
        self.btn_xml_dl.setFlat(False)
        self.btn_xml_dl.setObjectName("btn_xml_dl")
        self.gridLayout_3.addWidget(self.btn_xml_dl, 2, 0, 1, 2)
        self.grp_md_owner = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grp_md_owner.setMinimumSize(QtCore.QSize(250, 150))
        self.grp_md_owner.setMaximumSize(QtCore.QSize(16777211, 700))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_md_owner.setFont(font)
        self.grp_md_owner.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.grp_md_owner.setObjectName("grp_md_owner")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.grp_md_owner)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.val_owner_email = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_email.setMinimumSize(QtCore.QSize(225, 0))
        self.val_owner_email.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.val_owner_email.setFont(font)
        self.val_owner_email.setAutoFillBackground(False)
        self.val_owner_email.setOpenExternalLinks(True)
        self.val_owner_email.setObjectName("val_owner_email")
        self.gridLayout_8.addWidget(self.val_owner_email, 1, 0, 1, 1)
        self.val_owner_address = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_address.setMinimumSize(QtCore.QSize(225, 0))
        self.val_owner_address.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner_address.setFont(font)
        self.val_owner_address.setObjectName("val_owner_address")
        self.gridLayout_8.addWidget(self.val_owner_address, 3, 0, 1, 1)
        self.val_owner_phone = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_phone.setMinimumSize(QtCore.QSize(225, 0))
        self.val_owner_phone.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner_phone.setFont(font)
        self.val_owner_phone.setObjectName("val_owner_phone")
        self.gridLayout_8.addWidget(self.val_owner_phone, 2, 0, 1, 1)
        self.val_owner_city = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_city.setMinimumSize(QtCore.QSize(225, 0))
        self.val_owner_city.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner_city.setFont(font)
        self.val_owner_city.setObjectName("val_owner_city")
        self.gridLayout_8.addWidget(self.val_owner_city, 4, 0, 1, 1)
        self.val_owner_country = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_country.setMinimumSize(QtCore.QSize(225, 0))
        self.val_owner_country.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner_country.setFont(font)
        self.val_owner_country.setObjectName("val_owner_country")
        self.gridLayout_8.addWidget(self.val_owner_country, 5, 0, 1, 1)
        self.val_owner_name = QtWidgets.QLabel(self.grp_md_owner)
        self.val_owner_name.setMinimumSize(QtCore.QSize(225, 16))
        self.val_owner_name.setMaximumSize(QtCore.QSize(50, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_owner_name.setFont(font)
        self.val_owner_name.setScaledContents(True)
        self.val_owner_name.setObjectName("val_owner_name")
        self.gridLayout_8.addWidget(self.val_owner_name, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem19, 6, 0, 1, 1)
        self.gridLayout_3.addWidget(self.grp_md_owner, 0, 0, 1, 1)
        self.grp_md_properties = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grp_md_properties.setMinimumSize(QtCore.QSize(250, 150))
        self.grp_md_properties.setMaximumSize(QtCore.QSize(16777215, 700))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.grp_md_properties.setFont(font)
        self.grp_md_properties.setObjectName("grp_md_properties")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.grp_md_properties)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lbl_md_date_crea = QtWidgets.QLabel(self.grp_md_properties)
        self.lbl_md_date_crea.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_md_date_crea.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_md_date_crea.setFont(font)
        self.lbl_md_date_crea.setObjectName("lbl_md_date_crea")
        self.gridLayout_10.addWidget(self.lbl_md_date_crea, 1, 1, 1, 1)
        self.lbl_md_lang = QtWidgets.QLabel(self.grp_md_properties)
        self.lbl_md_lang.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_md_lang.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_md_lang.setFont(font)
        self.lbl_md_lang.setObjectName("lbl_md_lang")
        self.gridLayout_10.addWidget(self.lbl_md_lang, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem20, 1, 2, 1, 1)
        self.ico_md_date_update = QtWidgets.QLabel(self.grp_md_properties)
        self.ico_md_date_update.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_md_date_update.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ico_md_date_update.setFont(font)
        self.ico_md_date_update.setText("")
        self.ico_md_date_update.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/calendar_blue.svg"))
        self.ico_md_date_update.setScaledContents(True)
        self.ico_md_date_update.setObjectName("ico_md_date_update")
        self.gridLayout_10.addWidget(self.ico_md_date_update, 2, 0, 1, 1)
        self.ico_md_date_crea = QtWidgets.QLabel(self.grp_md_properties)
        self.ico_md_date_crea.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_md_date_crea.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ico_md_date_crea.setFont(font)
        self.ico_md_date_crea.setText("")
        self.ico_md_date_crea.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/calendar-plus-o.svg"))
        self.ico_md_date_crea.setScaledContents(True)
        self.ico_md_date_crea.setObjectName("ico_md_date_crea")
        self.gridLayout_10.addWidget(self.ico_md_date_crea, 1, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem21, 2, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(470, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem22, 0, 2, 1, 1)
        self.val_md_date_crea = QtWidgets.QLabel(self.grp_md_properties)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_md_date_crea.setFont(font)
        self.val_md_date_crea.setObjectName("val_md_date_crea")
        self.gridLayout_10.addWidget(self.val_md_date_crea, 1, 3, 1, 1)
        self.lbl_md_date_update = QtWidgets.QLabel(self.grp_md_properties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_md_date_update.sizePolicy().hasHeightForWidth())
        self.lbl_md_date_update.setSizePolicy(sizePolicy)
        self.lbl_md_date_update.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_md_date_update.setMaximumSize(QtCore.QSize(50, 32))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_md_date_update.setFont(font)
        self.lbl_md_date_update.setScaledContents(True)
        self.lbl_md_date_update.setWordWrap(False)
        self.lbl_md_date_update.setObjectName("lbl_md_date_update")
        self.gridLayout_10.addWidget(self.lbl_md_date_update, 2, 1, 1, 1)
        self.ico_md_lang = QtWidgets.QLabel(self.grp_md_properties)
        self.ico_md_lang.setMinimumSize(QtCore.QSize(16, 16))
        self.ico_md_lang.setMaximumSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ico_md_lang.setFont(font)
        self.ico_md_lang.setText("")
        self.ico_md_lang.setPixmap(QtGui.QPixmap(":/plugins/Isogeo/resources/metadata/language.svg"))
        self.ico_md_lang.setScaledContents(True)
        self.ico_md_lang.setObjectName("ico_md_lang")
        self.gridLayout_10.addWidget(self.ico_md_lang, 0, 0, 1, 1)
        self.val_md_date_update = QtWidgets.QLabel(self.grp_md_properties)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_md_date_update.setFont(font)
        self.val_md_date_update.setObjectName("val_md_date_update")
        self.gridLayout_10.addWidget(self.val_md_date_update, 2, 3, 1, 1)
        self.val_md_lang = QtWidgets.QLabel(self.grp_md_properties)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.val_md_lang.setFont(font)
        self.val_md_lang.setObjectName("val_md_lang")
        self.gridLayout_10.addWidget(self.val_md_lang, 0, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem23, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.grp_md_properties, 0, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.md_advanced)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_addtomap = QtWidgets.QPushButton(dlg_metadata_details)
        self.btn_addtomap.setMinimumSize(QtCore.QSize(150, 25))
        self.btn_addtomap.setObjectName("btn_addtomap")
        self.horizontalLayout.addWidget(self.btn_addtomap)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.btn_ok_cancel = QtWidgets.QDialogButtonBox(dlg_metadata_details)
        self.btn_ok_cancel.setMinimumSize(QtCore.QSize(150, 25))
        self.btn_ok_cancel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.btn_ok_cancel.setAutoFillBackground(True)
        self.btn_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.btn_ok_cancel.setCenterButtons(False)
        self.btn_ok_cancel.setObjectName("btn_ok_cancel")
        self.horizontalLayout.addWidget(self.btn_ok_cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.retranslateUi(dlg_metadata_details)
        self.li_menu.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(3)
        self.li_menu.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.btn_ok_cancel.rejected.connect(dlg_metadata_details.reject)
        self.btn_ok_cancel.accepted.connect(dlg_metadata_details.accept)
        QtCore.QMetaObject.connectSlotsByName(dlg_metadata_details)

    def retranslateUi(self, dlg_metadata_details):
        _translate = QtCore.QCoreApplication.translate
        dlg_metadata_details.setWindowTitle(_translate("dlg_metadata_details", "Isogeo Metadata"))
        self.li_menu.setSortingEnabled(False)
        __sortingEnabled = self.li_menu.isSortingEnabled()
        self.li_menu.setSortingEnabled(False)
        item = self.li_menu.item(0)
        item.setText(_translate("dlg_metadata_details", "General"))
        item = self.li_menu.item(1)
        item.setText(_translate("dlg_metadata_details", "Feature attributes"))
        item = self.li_menu.item(2)
        item.setText(_translate("dlg_metadata_details", "Contacts"))
        item = self.li_menu.item(3)
        item.setText(_translate("dlg_metadata_details", "History"))
        item = self.li_menu.item(4)
        item.setText(_translate("dlg_metadata_details", "Geography"))
        item = self.li_menu.item(5)
        item.setText(_translate("dlg_metadata_details", "Quality"))
        item = self.li_menu.item(6)
        item.setText(_translate("dlg_metadata_details", "Licenses"))
        item = self.li_menu.item(7)
        item.setText(_translate("dlg_metadata_details", "Advanced"))
        self.li_menu.setSortingEnabled(__sortingEnabled)
        self.btn_md_edit.setText(_translate("dlg_metadata_details", "Edit it on Isogeo"))
        self.val_owner.setToolTip(_translate("dlg_metadata_details", "Metadata owner"))
        self.val_owner.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.val_group_themes.setToolTip(_translate("dlg_metadata_details", "Group themes"))
        self.val_group_themes.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.ico_keywords.setToolTip(_translate("dlg_metadata_details", "Keywords"))
        self.val_keywords.setToolTip(_translate("dlg_metadata_details", "Keywords"))
        self.val_keywords.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.ico_inspire_themes.setToolTip(_translate("dlg_metadata_details", "INSPIRE themes"))
        self.val_inspire_themes.setToolTip(_translate("dlg_metadata_details", "INSPIRE themes"))
        self.val_inspire_themes.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.ico_abstract.setToolTip(_translate("dlg_metadata_details", "Abstract"))
        self.val_abstract.setToolTip(_translate("dlg_metadata_details", "Abstract"))
        self.val_abstract.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.tbl_attributes.setSortingEnabled(True)
        item = self.tbl_attributes.horizontalHeaderItem(0)
        item.setText(_translate("dlg_metadata_details", "Name"))
        item = self.tbl_attributes.horizontalHeaderItem(1)
        item.setText(_translate("dlg_metadata_details", "Alias"))
        item = self.tbl_attributes.horizontalHeaderItem(2)
        item.setText(_translate("dlg_metadata_details", "Type"))
        item = self.tbl_attributes.horizontalHeaderItem(3)
        item.setText(_translate("dlg_metadata_details", "Description"))
        self.grp_pointof.setTitle(_translate("dlg_metadata_details", "Point of contact"))
        self.val_ct_pointof.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.groupBox.setTitle(_translate("dlg_metadata_details", "Others contacts"))
        self.val_ct_other.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_history.setTitle(_translate("dlg_metadata_details", "Data history"))
        self.val_frequency.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_frequency.setText(_translate("dlg_metadata_details", "Updated every:"))
        self.val_data_update.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_data_update.setText(_translate("dlg_metadata_details", "Last update:"))
        self.val_data_crea.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_data_crea.setText(_translate("dlg_metadata_details", "Creation date:"))
        self.lbl_valid_comment.setText(_translate("dlg_metadata_details", "Validity comment:"))
        self.val_valid_comment.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.val_valid_end.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_valid_start.setText(_translate("dlg_metadata_details", "Validity period start:"))
        self.val_valid_start.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_valid_end.setText(_translate("dlg_metadata_details", "Validity period end:"))
        self.grp_collect_context.setTitle(_translate("dlg_metadata_details", "Collection context"))
        self.val_context.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_collect_method.setTitle(_translate("dlg_metadata_details", "Collection method"))
        self.val_method.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.mGroupBox.setTitle(_translate("dlg_metadata_details", "Last modifications"))
        self.tbl_events.setSortingEnabled(True)
        item = self.tbl_events.horizontalHeaderItem(0)
        item.setText(_translate("dlg_metadata_details", "Date"))
        item = self.tbl_events.horizontalHeaderItem(1)
        item.setText(_translate("dlg_metadata_details", "Description"))
        self.grp_technic.setTitle(_translate("dlg_metadata_details", "Technical informations"))
        self.val_format.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_format.setText(_translate("dlg_metadata_details", "Format:"))
        self.lbl_feat_count.setText(_translate("dlg_metadata_details", "Features count:"))
        self.val_feat_count.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_geometry.setText(_translate("dlg_metadata_details", "Geometry type:"))
        self.val_geometry.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.val_scale.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_scale.setText(_translate("dlg_metadata_details", "Scale:"))
        self.lbl_srs.setText(_translate("dlg_metadata_details", "SRS:"))
        self.val_srs.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_resolution.setText(_translate("dlg_metadata_details", "Resolution:"))
        self.val_resolution.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_geoContext.setTitle(_translate("dlg_metadata_details", "Geographical context"))
        self.val_geoContext.setToolTip(_translate("dlg_metadata_details", "Geographical context"))
        self.val_geoContext.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_bbox.setTitle(_translate("dlg_metadata_details", "Bounding box preview"))
        self.grp_specification.setTitle(_translate("dlg_metadata_details", "Specifications"))
        self.val_specifications.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_topoConsist.setTitle(_translate("dlg_metadata_details", "Topological consistency"))
        self.val_topology.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.grp_licences.setTitle(_translate("dlg_metadata_details", "Licenses"))
        self.val_licenses.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.groupBox_2.setTitle(_translate("dlg_metadata_details", "Limitations"))
        self.val_limitations.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.btn_xml_dl.setText(_translate("dlg_metadata_details", "Download metadata XML"))
        self.grp_md_owner.setTitle(_translate("dlg_metadata_details", "Metadata owner"))
        self.val_owner_email.setText(_translate("dlg_metadata_details", "wg_email"))
        self.val_owner_address.setText(_translate("dlg_metadata_details", "wg_address"))
        self.val_owner_phone.setText(_translate("dlg_metadata_details", "wg_phone"))
        self.val_owner_city.setText(_translate("dlg_metadata_details", "wg_pc_city"))
        self.val_owner_country.setText(_translate("dlg_metadata_details", "wg_country"))
        self.val_owner_name.setText(_translate("dlg_metadata_details", "wg_owner"))
        self.grp_md_properties.setTitle(_translate("dlg_metadata_details", "Metadata properties"))
        self.lbl_md_date_crea.setText(_translate("dlg_metadata_details", "Created:"))
        self.lbl_md_lang.setText(_translate("dlg_metadata_details", "Language: "))
        self.val_md_date_crea.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.lbl_md_date_update.setText(_translate("dlg_metadata_details", "Last update:"))
        self.val_md_date_update.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.val_md_lang.setText(_translate("dlg_metadata_details", "TextLabel"))
        self.btn_addtomap.setText(_translate("dlg_metadata_details", "addButton"))

from qgis.gui import QgsMapCanvas
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlg_metadata_details = QtWidgets.QDialog()
    ui = Ui_dlg_metadata_details()
    ui.setupUi(dlg_metadata_details)
    dlg_metadata_details.show()
    sys.exit(app.exec_())

