# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\metadata\ui_md_details.ui'
#
# Created: Tue Mar 14 10:47:40 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ui_main_window(object):
    def setupUi(self, ui_main_window):
        ui_main_window.setObjectName(_fromUtf8("ui_main_window"))
        ui_main_window.setWindowModality(QtCore.Qt.WindowModal)
        ui_main_window.resize(905, 834)
        ui_main_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout_2 = QtGui.QGridLayout(ui_main_window)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.stackedWidget = QtGui.QStackedWidget(ui_main_window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.md_general = QtGui.QWidget()
        self.md_general.setObjectName(_fromUtf8("md_general"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.md_general)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.lbl_title = QtGui.QLabel(self.md_general)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setWordWrap(True)
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.verticalLayout_11.addWidget(self.lbl_title)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_owner = QtGui.QLabel(self.md_general)
        self.lbl_owner.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_owner.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_owner.setText(_fromUtf8(""))
        self.lbl_owner.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/users.svg")))
        self.lbl_owner.setScaledContents(True)
        self.lbl_owner.setObjectName(_fromUtf8("lbl_owner"))
        self.horizontalLayout_2.addWidget(self.lbl_owner)
        self.val_owner = QtGui.QTextEdit(self.md_general)
        self.val_owner.setMaximumSize(QtCore.QSize(16777215, 23))
        self.val_owner.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.val_owner.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.val_owner.setReadOnly(True)
        self.val_owner.setObjectName(_fromUtf8("val_owner"))
        self.horizontalLayout_2.addWidget(self.val_owner)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lbl_keywords = QtGui.QLabel(self.md_general)
        self.lbl_keywords.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_keywords.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_keywords.setText(_fromUtf8(""))
        self.lbl_keywords.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/tag.svg")))
        self.lbl_keywords.setScaledContents(True)
        self.lbl_keywords.setWordWrap(False)
        self.lbl_keywords.setObjectName(_fromUtf8("lbl_keywords"))
        self.horizontalLayout_8.addWidget(self.lbl_keywords)
        self.val_keywords = QtGui.QTextEdit(self.md_general)
        self.val_keywords.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.val_keywords.setReadOnly(True)
        self.val_keywords.setObjectName(_fromUtf8("val_keywords"))
        self.horizontalLayout_8.addWidget(self.val_keywords)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.lbl_inspire_themes = QtGui.QLabel(self.md_general)
        self.lbl_inspire_themes.setMinimumSize(QtCore.QSize(16, 16))
        self.lbl_inspire_themes.setMaximumSize(QtCore.QSize(16, 16))
        self.lbl_inspire_themes.setText(_fromUtf8(""))
        self.lbl_inspire_themes.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/leaf.svg")))
        self.lbl_inspire_themes.setScaledContents(True)
        self.lbl_inspire_themes.setObjectName(_fromUtf8("lbl_inspire_themes"))
        self.horizontalLayout_17.addWidget(self.lbl_inspire_themes)
        self.val_inspire_themes = QtGui.QTextEdit(self.md_general)
        self.val_inspire_themes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.val_inspire_themes.setReadOnly(True)
        self.val_inspire_themes.setObjectName(_fromUtf8("val_inspire_themes"))
        self.horizontalLayout_17.addWidget(self.val_inspire_themes)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.val_abstract = QtGui.QTextEdit(self.md_general)
        self.val_abstract.setEnabled(True)
        self.val_abstract.setAutoFillBackground(True)
        self.val_abstract.setFrameShape(QtGui.QFrame.StyledPanel)
        self.val_abstract.setFrameShadow(QtGui.QFrame.Sunken)
        self.val_abstract.setLineWidth(0)
        self.val_abstract.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.val_abstract.setReadOnly(True)
        self.val_abstract.setObjectName(_fromUtf8("val_abstract"))
        self.gridLayout_4.addWidget(self.val_abstract, 1, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.md_general)
        self.md_feat_attributes = QtGui.QWidget()
        self.md_feat_attributes.setObjectName(_fromUtf8("md_feat_attributes"))
        self.gridLayout = QtGui.QGridLayout(self.md_feat_attributes)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbl_attributes = QtGui.QTableWidget(self.md_feat_attributes)
        self.tbl_attributes.setObjectName(_fromUtf8("tbl_attributes"))
        self.tbl_attributes.setColumnCount(4)
        self.tbl_attributes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_attributes.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tbl_attributes, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.md_feat_attributes)
        self.md_contacts = QtGui.QWidget()
        self.md_contacts.setObjectName(_fromUtf8("md_contacts"))
        self.gridLayout_7 = QtGui.QGridLayout(self.md_contacts)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.val_contact = QtGui.QTextEdit(self.md_contacts)
        self.val_contact.setReadOnly(True)
        self.val_contact.setObjectName(_fromUtf8("val_contact"))
        self.gridLayout_7.addWidget(self.val_contact, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.md_contacts)
        self.md_history = QtGui.QWidget()
        self.md_history.setObjectName(_fromUtf8("md_history"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.md_history)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.grp_history = QtGui.QGroupBox(self.md_history)
        self.grp_history.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_history.setObjectName(_fromUtf8("grp_history"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grp_history)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.line_4 = QtGui.QFrame(self.grp_history)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 0, 3, 4, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_29 = QtGui.QLabel(self.grp_history)
        self.label_29.setMaximumSize(QtCore.QSize(16, 16))
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar.svg")))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_19.addWidget(self.label_29)
        self.lbl_data_updt = QtGui.QLabel(self.grp_history)
        self.lbl_data_updt.setObjectName(_fromUtf8("lbl_data_updt"))
        self.horizontalLayout_19.addWidget(self.lbl_data_updt)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.val_data_updt = QtGui.QLabel(self.grp_history)
        self.val_data_updt.setObjectName(_fromUtf8("val_data_updt"))
        self.horizontalLayout_19.addWidget(self.val_data_updt)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.gridLayout_5.addLayout(self.verticalLayout_14, 1, 0, 2, 1)
        self.line = QtGui.QFrame(self.grp_history)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_5.addWidget(self.line, 0, 1, 3, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem1, 3, 0, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_30 = QtGui.QLabel(self.grp_history)
        self.label_30.setMaximumSize(QtCore.QSize(16, 16))
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar-o.svg")))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_20.addWidget(self.label_30)
        self.lbl_valid_start = QtGui.QLabel(self.grp_history)
        self.lbl_valid_start.setObjectName(_fromUtf8("lbl_valid_start"))
        self.horizontalLayout_20.addWidget(self.lbl_valid_start)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.val_valid_start = QtGui.QLabel(self.grp_history)
        self.val_valid_start.setObjectName(_fromUtf8("val_valid_start"))
        self.horizontalLayout_20.addWidget(self.val_valid_start)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_31 = QtGui.QLabel(self.grp_history)
        self.label_31.setMaximumSize(QtCore.QSize(16, 16))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar.svg")))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_21.addWidget(self.label_31)
        self.lbl_valid_end = QtGui.QLabel(self.grp_history)
        self.lbl_valid_end.setObjectName(_fromUtf8("lbl_valid_end"))
        self.horizontalLayout_21.addWidget(self.lbl_valid_end)
        spacerItem3 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.val_valid_end = QtGui.QLabel(self.grp_history)
        self.val_valid_end.setObjectName(_fromUtf8("val_valid_end"))
        self.horizontalLayout_21.addWidget(self.val_valid_end)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.gridLayout_5.addLayout(self.verticalLayout_15, 1, 2, 2, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_28 = QtGui.QLabel(self.grp_history)
        self.label_28.setMaximumSize(QtCore.QSize(16, 16))
        self.label_28.setText(_fromUtf8(""))
        self.label_28.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar-o.svg")))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_18.addWidget(self.label_28)
        self.lbl_data_crea = QtGui.QLabel(self.grp_history)
        self.lbl_data_crea.setObjectName(_fromUtf8("lbl_data_crea"))
        self.horizontalLayout_18.addWidget(self.lbl_data_crea)
        spacerItem4 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.val_data_crea = QtGui.QLabel(self.grp_history)
        self.val_data_crea.setObjectName(_fromUtf8("val_data_crea"))
        self.horizontalLayout_18.addWidget(self.val_data_crea)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_18.addWidget(self.grp_history)
        self.groupBox = QtGui.QGroupBox(self.md_history)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.lbl_method = QtGui.QLabel(self.groupBox)
        self.lbl_method.setObjectName(_fromUtf8("lbl_method"))
        self.verticalLayout_17.addWidget(self.lbl_method)
        self.val_method = QtGui.QTextEdit(self.groupBox)
        self.val_method.setMinimumSize(QtCore.QSize(271, 0))
        self.val_method.setReadOnly(True)
        self.val_method.setObjectName(_fromUtf8("val_method"))
        self.verticalLayout_17.addWidget(self.val_method)
        self.lbl_context = QtGui.QLabel(self.groupBox)
        self.lbl_context.setObjectName(_fromUtf8("lbl_context"))
        self.verticalLayout_17.addWidget(self.lbl_context)
        self.val_context = QtGui.QTextEdit(self.groupBox)
        self.val_context.setMinimumSize(QtCore.QSize(271, 0))
        self.val_context.setReadOnly(True)
        self.val_context.setObjectName(_fromUtf8("val_context"))
        self.verticalLayout_17.addWidget(self.val_context)
        self.verticalLayout_18.addWidget(self.groupBox)
        self.mGroupBox = QgsCollapsibleGroupBox(self.md_history)
        self.mGroupBox.setCollapsed(True)
        self.mGroupBox.setObjectName(_fromUtf8("mGroupBox"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.list_events = QtGui.QListWidget(self.mGroupBox)
        self.list_events.setMinimumSize(QtCore.QSize(215, 0))
        self.list_events.setSelectionRectVisible(True)
        self.list_events.setObjectName(_fromUtf8("list_events"))
        self.verticalLayout_16.addWidget(self.list_events)
        self.verticalLayout_18.addWidget(self.mGroupBox)
        self.stackedWidget.addWidget(self.md_history)
        self.md_geography = QtGui.QWidget()
        self.md_geography.setObjectName(_fromUtf8("md_geography"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.md_geography)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.grp_technic = QtGui.QGroupBox(self.md_geography)
        self.grp_technic.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_technic.setObjectName(_fromUtf8("grp_technic"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grp_technic)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_32 = QtGui.QLabel(self.grp_technic)
        self.label_32.setMaximumSize(QtCore.QSize(16, 16))
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/cube.svg")))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_7.addWidget(self.label_32)
        self.lbl_format = QtGui.QLabel(self.grp_technic)
        self.lbl_format.setObjectName(_fromUtf8("lbl_format"))
        self.horizontalLayout_7.addWidget(self.lbl_format)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.val_format = QtGui.QLabel(self.grp_technic)
        self.val_format.setObjectName(_fromUtf8("val_format"))
        self.horizontalLayout_7.addWidget(self.val_format)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_33 = QtGui.QLabel(self.grp_technic)
        self.label_33.setMaximumSize(QtCore.QSize(16, 16))
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/globe.svg")))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_22.addWidget(self.label_33)
        self.lbl_srs = QtGui.QLabel(self.grp_technic)
        self.lbl_srs.setObjectName(_fromUtf8("lbl_srs"))
        self.horizontalLayout_22.addWidget(self.lbl_srs)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.val_srs = QtGui.QLabel(self.grp_technic)
        self.val_srs.setObjectName(_fromUtf8("val_srs"))
        self.horizontalLayout_22.addWidget(self.val_srs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_38 = QtGui.QLabel(self.grp_technic)
        self.label_38.setMaximumSize(QtCore.QSize(16, 16))
        self.label_38.setText(_fromUtf8(""))
        self.label_38.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/cube.svg")))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_27.addWidget(self.label_38)
        self.lbl_format_4 = QtGui.QLabel(self.grp_technic)
        self.lbl_format_4.setObjectName(_fromUtf8("lbl_format_4"))
        self.horizontalLayout_27.addWidget(self.lbl_format_4)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem7)
        self.val_format_4 = QtGui.QLabel(self.grp_technic)
        self.val_format_4.setObjectName(_fromUtf8("val_format_4"))
        self.horizontalLayout_27.addWidget(self.val_format_4)
        self.verticalLayout_21.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_39 = QtGui.QLabel(self.grp_technic)
        self.label_39.setMaximumSize(QtCore.QSize(16, 16))
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/globe.svg")))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_28.addWidget(self.label_39)
        self.lbl_srs_4 = QtGui.QLabel(self.grp_technic)
        self.lbl_srs_4.setObjectName(_fromUtf8("lbl_srs_4"))
        self.horizontalLayout_28.addWidget(self.lbl_srs_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem8)
        self.val_srs_4 = QtGui.QLabel(self.grp_technic)
        self.val_srs_4.setObjectName(_fromUtf8("val_srs_4"))
        self.horizontalLayout_28.addWidget(self.val_srs_4)
        self.verticalLayout_21.addLayout(self.horizontalLayout_28)
        self.gridLayout_6.addLayout(self.verticalLayout_21, 1, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.grp_technic)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem9)
        self.widget = QtGui.QWidget(self.md_geography)
        self.widget.setMinimumSize(QtCore.QSize(200, 200))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_22.addWidget(self.widget)
        self.stackedWidget.addWidget(self.md_geography)
        self.md_cgu = QtGui.QWidget()
        self.md_cgu.setObjectName(_fromUtf8("md_cgu"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.md_cgu)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lbl_licenses = QtGui.QLabel(self.md_cgu)
        self.lbl_licenses.setObjectName(_fromUtf8("lbl_licenses"))
        self.verticalLayout_3.addWidget(self.lbl_licenses)
        self.val_licenses = QtGui.QTextEdit(self.md_cgu)
        self.val_licenses.setReadOnly(True)
        self.val_licenses.setObjectName(_fromUtf8("val_licenses"))
        self.verticalLayout_3.addWidget(self.val_licenses)
        self.lbl_limitations = QtGui.QLabel(self.md_cgu)
        self.lbl_limitations.setObjectName(_fromUtf8("lbl_limitations"))
        self.verticalLayout_3.addWidget(self.lbl_limitations)
        self.val_limitations = QtGui.QTextEdit(self.md_cgu)
        self.val_limitations.setReadOnly(True)
        self.val_limitations.setObjectName(_fromUtf8("val_limitations"))
        self.verticalLayout_3.addWidget(self.val_limitations)
        self.stackedWidget.addWidget(self.md_cgu)
        self.md_advanced = QtGui.QWidget()
        self.md_advanced.setObjectName(_fromUtf8("md_advanced"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.md_advanced)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrollArea_2 = QtGui.QScrollArea(self.md_advanced)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 719, 763))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grp_technic_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grp_technic_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_technic_2.setObjectName(_fromUtf8("grp_technic_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.grp_technic_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_40 = QtGui.QLabel(self.grp_technic_2)
        self.label_40.setMaximumSize(QtCore.QSize(16, 16))
        self.label_40.setText(_fromUtf8(""))
        self.label_40.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/cube.svg")))
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_4.addWidget(self.label_40)
        self.lbl_format_5 = QtGui.QLabel(self.grp_technic_2)
        self.lbl_format_5.setObjectName(_fromUtf8("lbl_format_5"))
        self.horizontalLayout_4.addWidget(self.lbl_format_5)
        spacerItem10 = QtGui.QSpacerItem(470, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.val_format_5 = QtGui.QLabel(self.grp_technic_2)
        self.val_format_5.setObjectName(_fromUtf8("val_format_5"))
        self.horizontalLayout_4.addWidget(self.val_format_5)
        self.gridLayout_3.addWidget(self.grp_technic_2, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.md_advanced)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.md_edit_button = QtGui.QPushButton(ui_main_window)
        self.md_edit_button.setEnabled(False)
        self.md_edit_button.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/pencil.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.md_edit_button.setIcon(icon)
        self.md_edit_button.setCheckable(False)
        self.md_edit_button.setDefault(False)
        self.md_edit_button.setFlat(True)
        self.md_edit_button.setObjectName(_fromUtf8("md_edit_button"))
        self.gridLayout_2.addWidget(self.md_edit_button, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ui_main_window)
        self.buttonBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.li_menu = QtGui.QListWidget(ui_main_window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.li_menu.sizePolicy().hasHeightForWidth())
        self.li_menu.setSizePolicy(sizePolicy)
        self.li_menu.setMinimumSize(QtCore.QSize(100, 200))
        self.li_menu.setMaximumSize(QtCore.QSize(153, 16777215))
        self.li_menu.setStyleSheet(_fromUtf8("QListWidget{\n"
"    background-color: rgb(69, 69, 69, 220);\n"
"    outline: 0;\n"
"}\n"
"QListWidget::item {\n"
"    color: white;\n"
"    padding: 3px;\n"
"}\n"
"QListWidget::item::selected {\n"
"    color: black;\n"
"    background-color:palette(Window);\n"
"    padding-right: 0px;\n"
"}"))
        self.li_menu.setFrameShape(QtGui.QFrame.Box)
        self.li_menu.setLineWidth(0)
        self.li_menu.setIconSize(QtCore.QSize(32, 32))
        self.li_menu.setUniformItemSizes(True)
        self.li_menu.setObjectName(_fromUtf8("li_menu"))
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/bookmark.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/list-alt.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/phone.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/calendar.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/globe.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/gavel.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.li_menu.addItem(item)
        item = QtGui.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/Isogeo/resources/code.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.li_menu.addItem(item)
        self.gridLayout_2.addWidget(self.li_menu, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.retranslateUi(ui_main_window)
        self.stackedWidget.setCurrentIndex(0)
        self.li_menu.setCurrentRow(-1)
        QtCore.QObject.connect(self.li_menu, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(ui_main_window)

    def retranslateUi(self, ui_main_window):
        ui_main_window.setWindowTitle(_translate("ui_main_window", "Isogeo Metadata", None))
        self.lbl_title.setText(_translate("ui_main_window", "<html><head/><body><p><span style=\" font-style:italic;\">No title</span></p></body></html>", None))
        self.tbl_attributes.setSortingEnabled(True)
        item = self.tbl_attributes.horizontalHeaderItem(0)
        item.setText(_translate("ui_main_window", "Name", None))
        item = self.tbl_attributes.horizontalHeaderItem(1)
        item.setText(_translate("ui_main_window", "Alias", None))
        item = self.tbl_attributes.horizontalHeaderItem(2)
        item.setText(_translate("ui_main_window", "Type", None))
        item = self.tbl_attributes.horizontalHeaderItem(3)
        item.setText(_translate("ui_main_window", "Description", None))
        self.grp_history.setTitle(_translate("ui_main_window", "Data history", None))
        self.lbl_data_updt.setText(_translate("ui_main_window", "Last update:", None))
        self.val_data_updt.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_valid_start.setText(_translate("ui_main_window", "Validity period start:", None))
        self.val_valid_start.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_valid_end.setText(_translate("ui_main_window", "Validity period end:", None))
        self.val_valid_end.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_data_crea.setText(_translate("ui_main_window", "Creation date:", None))
        self.val_data_crea.setText(_translate("ui_main_window", "TextLabel", None))
        self.groupBox.setTitle(_translate("ui_main_window", "Collection", None))
        self.lbl_method.setText(_translate("ui_main_window", "Collection method", None))
        self.lbl_context.setText(_translate("ui_main_window", "Collection context", None))
        self.mGroupBox.setTitle(_translate("ui_main_window", "Last modifications", None))
        self.grp_technic.setTitle(_translate("ui_main_window", "Technical informations", None))
        self.lbl_format.setText(_translate("ui_main_window", "Format:", None))
        self.val_format.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_srs.setText(_translate("ui_main_window", "SRS:", None))
        self.val_srs.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_format_4.setText(_translate("ui_main_window", "Features count:", None))
        self.val_format_4.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_srs_4.setText(_translate("ui_main_window", "Geometry type:", None))
        self.val_srs_4.setText(_translate("ui_main_window", "TextLabel", None))
        self.lbl_licenses.setText(_translate("ui_main_window", "Licenses", None))
        self.lbl_limitations.setText(_translate("ui_main_window", "Limitations", None))
        self.grp_technic_2.setTitle(_translate("ui_main_window", "Technical informations", None))
        self.lbl_format_5.setText(_translate("ui_main_window", "metadata language", None))
        self.val_format_5.setText(_translate("ui_main_window", "TextLabel", None))
        self.md_edit_button.setText(_translate("ui_main_window", "Edit it on Isogeo", None))
        __sortingEnabled = self.li_menu.isSortingEnabled()
        self.li_menu.setSortingEnabled(False)
        item = self.li_menu.item(0)
        item.setText(_translate("ui_main_window", "General", None))
        item = self.li_menu.item(1)
        item.setText(_translate("ui_main_window", "Feature attributes", None))
        item = self.li_menu.item(2)
        item.setText(_translate("ui_main_window", "Contacts", None))
        item = self.li_menu.item(3)
        item.setText(_translate("ui_main_window", "History", None))
        item = self.li_menu.item(4)
        item.setText(_translate("ui_main_window", "Geography", None))
        item = self.li_menu.item(5)
        item.setText(_translate("ui_main_window", "Licenses", None))
        item = self.li_menu.item(6)
        item.setText(_translate("ui_main_window", "Advanced", None))
        self.li_menu.setSortingEnabled(__sortingEnabled)

from qgis.gui import QgsCollapsibleGroupBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ui_main_window = QtGui.QDialog()
    ui = Ui_ui_main_window()
    ui.setupUi(ui_main_window)
    ui_main_window.show()
    sys.exit(app.exec_())

